# Generated by Django 5.2.16 on 2026-07-30 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("sources", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("observed_at", models.DateTimeField(verbose_name="Vaatluse aeg")),
                ("is_current", models.BooleanField(default=False, verbose_name="Kehtiv")),
                ("item_count", models.PositiveIntegerField(default=0, verbose_name="Sündmusi")),
                ("imported_at", models.DateTimeField(auto_now_add=True, verbose_name="Imporditud")),
                (
                    "artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="event_snapshots",
                        to="sources.sourceartifact",
                        verbose_name="Algfail",
                    ),
                ),
                (
                    "import_run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="event_snapshot",
                        to="sources.importrun",
                        verbose_name="Impordikäivitus",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="event_snapshots",
                        to="sources.datasource",
                        verbose_name="Andmeallikas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sündmuste hetkeseis",
                "verbose_name_plural": "Sündmuste hetkeseisud",
                "ordering": ("-observed_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="EventItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("stable_key", models.CharField(max_length=200, verbose_name="Püsiv võti")),
                ("title", models.TextField(verbose_name="Pealkiri")),
                ("canonical_url", models.URLField(max_length=500, verbose_name="Viide")),
                (
                    "category",
                    models.CharField(blank=True, max_length=120, verbose_name="Kategooria"),
                ),
                ("summary", models.TextField(blank=True, verbose_name="Kokkuvõte")),
                ("starts_on", models.DateField(db_index=True, verbose_name="Algab")),
                ("ends_on", models.DateField(blank=True, null=True, verbose_name="Lõpeb")),
                ("starts_at", models.DateTimeField(blank=True, null=True, verbose_name="Algusaeg")),
                ("ends_at", models.DateTimeField(blank=True, null=True, verbose_name="Lõpuaeg")),
                (
                    "location",
                    models.CharField(blank=True, max_length=200, verbose_name="Toimumiskoht"),
                ),
                ("source_order", models.PositiveIntegerField(verbose_name="Järjekord allikas")),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="events.eventsnapshot",
                        verbose_name="Hetkeseis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sündmus",
                "verbose_name_plural": "Sündmused",
                "ordering": ("starts_on", "title", "stable_key"),
            },
        ),
        migrations.CreateModel(
            name="EventFeedState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "last_checked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Viimati kontrollitud"
                    ),
                ),
                (
                    "last_successful_sync_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Viimane edukas sünkroonimine"
                    ),
                ),
                (
                    "last_changed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Viimati muutunud"),
                ),
                (
                    "last_result",
                    models.CharField(
                        choices=[
                            ("never_run", "Pole veel käivitatud"),
                            ("imported", "Imporditud"),
                            ("unchanged", "Muutumatu"),
                            ("failed", "Ebaõnnestus"),
                        ],
                        default="never_run",
                        max_length=16,
                        verbose_name="Viimane tulemus",
                    ),
                ),
                (
                    "last_error_summary",
                    models.CharField(blank=True, max_length=500, verbose_name="Viimane veateade"),
                ),
                (
                    "remote_etag",
                    models.CharField(blank=True, max_length=200, verbose_name="Allika etag"),
                ),
                (
                    "remote_last_modified",
                    models.CharField(blank=True, max_length=100, verbose_name="Allika muutmisaeg"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Muudetud")),
                (
                    "source",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="event_feed_state",
                        to="sources.datasource",
                        verbose_name="Andmeallikas",
                    ),
                ),
                (
                    "current_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="events.eventsnapshot",
                        verbose_name="Kehtiv hetkeseis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sündmuste andmevoo olek",
                "verbose_name_plural": "Sündmuste andmevoo olekud",
            },
        ),
        migrations.AddConstraint(
            model_name="eventsnapshot",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("source",),
                name="eventsnapshot_one_current_per_source",
            ),
        ),
        migrations.AddIndex(
            model_name="eventitem",
            index=models.Index(
                fields=["snapshot", "starts_on"], name="events_even_snapsho_1ebdc7_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventitem",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "canonical_url"), name="eventitem_unique_url_per_snapshot"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventitem",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "stable_key"), name="eventitem_unique_key_per_snapshot"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("title", ""), _negated=True), name="eventitem_title_required"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ends_on__isnull", True),
                    ("ends_on__gte", models.F("starts_on")),
                    _connector="OR",
                ),
                name="eventitem_end_date_not_before_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ends_at__isnull", True),
                    models.Q(("ends_at__gte", models.F("starts_at")), ("starts_at__isnull", False)),
                    _connector="OR",
                ),
                name="eventitem_end_time_not_before_start",
            ),
        ),
    ]
