# Generated by Django 5.2.16 on 2026-07-30 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("sources", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("observed_at", models.DateTimeField(verbose_name="Vaatluse aeg")),
                ("is_current", models.BooleanField(default=False, verbose_name="Kehtiv")),
                ("item_count", models.PositiveIntegerField(default=0, verbose_name="Uudiseid")),
                ("imported_at", models.DateTimeField(auto_now_add=True, verbose_name="Imporditud")),
                (
                    "artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="news_snapshots",
                        to="sources.sourceartifact",
                        verbose_name="Algfail",
                    ),
                ),
                (
                    "import_run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="news_snapshot",
                        to="sources.importrun",
                        verbose_name="Impordikäivitus",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="news_snapshots",
                        to="sources.datasource",
                        verbose_name="Andmeallikas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Uudiste hetkeseis",
                "verbose_name_plural": "Uudiste hetkeseisud",
                "ordering": ("-observed_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="NewsItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("guid", models.CharField(max_length=500, verbose_name="GUID")),
                ("title", models.TextField(verbose_name="Pealkiri")),
                ("canonical_url", models.URLField(max_length=500, verbose_name="Viide")),
                ("published_at", models.DateTimeField(db_index=True, verbose_name="Avaldatud")),
                ("category", models.CharField(blank=True, max_length=120, verbose_name="Rubriik")),
                ("summary", models.TextField(blank=True, verbose_name="Kokkuvõte")),
                ("source_order", models.PositiveIntegerField(verbose_name="Järjekord allikas")),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="news.newssnapshot",
                        verbose_name="Hetkeseis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Uudis",
                "verbose_name_plural": "Uudised",
                "ordering": ("-published_at", "guid"),
            },
        ),
        migrations.CreateModel(
            name="NewsFeedState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "last_checked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Viimati kontrollitud"
                    ),
                ),
                (
                    "last_successful_sync_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Viimane edukas sünkroonimine"
                    ),
                ),
                (
                    "last_changed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Viimati muutunud"),
                ),
                (
                    "last_result",
                    models.CharField(
                        choices=[
                            ("never_run", "Pole veel käivitatud"),
                            ("imported", "Imporditud"),
                            ("unchanged", "Muutumatu"),
                            ("failed", "Ebaõnnestus"),
                        ],
                        default="never_run",
                        max_length=16,
                        verbose_name="Viimane tulemus",
                    ),
                ),
                (
                    "last_error_summary",
                    models.CharField(blank=True, max_length=500, verbose_name="Viimane veateade"),
                ),
                (
                    "remote_etag",
                    models.CharField(blank=True, max_length=200, verbose_name="Allika etag"),
                ),
                (
                    "remote_last_modified",
                    models.CharField(blank=True, max_length=100, verbose_name="Allika muutmisaeg"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Muudetud")),
                (
                    "source",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="news_feed_state",
                        to="sources.datasource",
                        verbose_name="Andmeallikas",
                    ),
                ),
                (
                    "current_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="news.newssnapshot",
                        verbose_name="Kehtiv hetkeseis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Uudiste andmevoo olek",
                "verbose_name_plural": "Uudiste andmevoo olekud",
            },
        ),
        migrations.AddConstraint(
            model_name="newssnapshot",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("source",),
                name="newssnapshot_one_current_per_source",
            ),
        ),
        migrations.AddIndex(
            model_name="newsitem",
            index=models.Index(
                fields=["snapshot", "-published_at"], name="news_newsit_snapsho_6d0bc5_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="newsitem",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "guid"), name="newsitem_unique_guid_per_snapshot"
            ),
        ),
        migrations.AddConstraint(
            model_name="newsitem",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "canonical_url"), name="newsitem_unique_url_per_snapshot"
            ),
        ),
        migrations.AddConstraint(
            model_name="newsitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("title", ""), _negated=True), name="newsitem_title_required"
            ),
        ),
    ]
