# Generated by Django 5.2.16 on 2026-08-10 06:37

import uuid

from django.db import migrations, models


def catalogue_what_is_still_retained(apps, schema_editor):
    """Seed the catalogue from every snapshot still in the database.

    A week of retained snapshots, so this recovers whatever has not been pruned
    yet — a handful of articles rather than a history. Everything published from
    here on is catalogued by the sync itself.

    The articles that scrolled out before this migration ran cannot be recovered
    from anything DashKoda holds; `discover_news_pages` reads their titles off
    the public site instead.
    """
    NewsItem = apps.get_model("news", "NewsItem")
    NewsResource = apps.get_model("news", "NewsResource")
    from django.utils import timezone

    from apps.visibility.ga4_paths import canonical_path

    now = timezone.now()
    seen: set[str] = set()
    # Newest first, so the most recent title of a repeated article wins.
    for item in NewsItem.objects.all().order_by("-published_at", "-id").iterator():
        path = canonical_path(item.canonical_url)
        if not path or path in seen:
            continue
        seen.add(path)
        NewsResource.objects.get_or_create(
            path=path,
            defaults={
                "canonical_url": item.canonical_url,
                "title": item.title,
                "published_at": item.published_at,
                "title_origin": "feed",
                "last_seen_at": now,
            },
        )


def forget_the_catalogue(apps, schema_editor):
    """Reverse: the table goes with the migration, so nothing to undo by hand."""


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                (
                    "canonical_url",
                    models.URLField(max_length=500, unique=True, verbose_name="Viide"),
                ),
                (
                    "path",
                    models.CharField(
                        db_index=True, max_length=500, unique=True, verbose_name="Tee"
                    ),
                ),
                ("title", models.TextField(verbose_name="Pealkiri")),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="Avaldatud"
                    ),
                ),
                (
                    "title_origin",
                    models.CharField(
                        choices=[("feed", "Uudisvoost"), ("page", "Avalikult lehelt")],
                        max_length=8,
                        verbose_name="Pealkirja allikas",
                    ),
                ),
                (
                    "first_seen_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Esmakordselt nähtud"),
                ),
                ("last_seen_at", models.DateTimeField(verbose_name="Viimati nähtud")),
            ],
            options={
                "verbose_name": "Uudise avalik leht",
                "verbose_name_plural": "Uudiste avalikud lehed",
                "ordering": ("-published_at", "path"),
                "indexes": [models.Index(fields=["path"], name="news_newsre_path_8b8663_idx")],
            },
        ),
        migrations.RunPython(catalogue_what_is_still_retained, forget_the_catalogue),
    ]
