# Generated by Django 5.2.16 on 2026-08-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_news_resource_catalogue"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsresource",
            name="category",
            field=models.CharField(
                blank=True, db_index=True, max_length=32, verbose_name="Kategooria"
            ),
        ),
    ]
