# Generated by Django 5.2.16 on 2026-07-28 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("sources", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalWorkSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "schema_version",
                    models.CharField(
                        help_text="Töövihiku enda deklareeritud versioon, mitte importija oma.",
                        max_length=16,
                        verbose_name="Skeemi versioon",
                    ),
                ),
                ("reporting_date", models.DateField(verbose_name="Andmete seis")),
                ("workbook_generated_at", models.DateTimeField(verbose_name="Töövihik loodud")),
                (
                    "source_file_modified_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Lähtefail muudetud"),
                ),
                ("imported_at", models.DateTimeField(auto_now_add=True, verbose_name="Imporditud")),
                ("is_current", models.BooleanField(default=False, verbose_name="Kehtiv")),
                (
                    "total_record_count",
                    models.PositiveIntegerField(default=0, verbose_name="Kirjeid kokku"),
                ),
                (
                    "open_record_count",
                    models.PositiveIntegerField(default=0, verbose_name="Avatud kirjeid"),
                ),
                (
                    "sent_record_count",
                    models.PositiveIntegerField(default=0, verbose_name="Välja saadetud"),
                ),
                (
                    "warning_record_count",
                    models.PositiveIntegerField(default=0, verbose_name="Hoiatustega kirjeid"),
                ),
                (
                    "artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legal_work_snapshots",
                        to="sources.sourceartifact",
                        verbose_name="Algfail",
                    ),
                ),
                (
                    "import_run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legal_work_snapshot",
                        to="sources.importrun",
                        verbose_name="Impordikäivitus",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legal_work_snapshots",
                        to="sources.datasource",
                        verbose_name="Andmeallikas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Õigusloome hetkeseis",
                "verbose_name_plural": "Õigusloome hetkeseisud",
                "ordering": ("-imported_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="LegalWorkItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("record_id", models.CharField(max_length=64, verbose_name="Kirje ID")),
                ("source_year", models.PositiveSmallIntegerField(verbose_name="Aasta")),
                (
                    "source_nr",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="Number"),
                ),
                ("topic", models.TextField(verbose_name="Teema")),
                (
                    "act_type",
                    models.CharField(blank=True, max_length=100, verbose_name="Õigusakti liik"),
                ),
                ("received_date", models.DateField(blank=True, null=True, verbose_name="Sisse")),
                (
                    "deadline_date",
                    models.DateField(blank=True, null=True, verbose_name="Arvamuse tähtaeg"),
                ),
                ("sent_date", models.DateField(blank=True, null=True, verbose_name="Välja")),
                (
                    "sent_status",
                    models.CharField(
                        choices=[
                            ("pending", "Ootel"),
                            ("sent", "Saadetud"),
                            ("not_sent", "Ei saadetud"),
                            ("invalid", "Vigane"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                        verbose_name="Saatmise olek",
                    ),
                ),
                ("recipient", models.CharField(blank=True, max_length=200, verbose_name="Kellele")),
                ("stage", models.CharField(blank=True, max_length=200, verbose_name="Hetkeseis")),
                (
                    "stage_key",
                    models.CharField(
                        blank=True, db_index=True, max_length=200, verbose_name="Seisu võti"
                    ),
                ),
                (
                    "next_step",
                    models.CharField(blank=True, max_length=300, verbose_name="Järgmiseks"),
                ),
                ("is_open", models.BooleanField(db_index=True, verbose_name="Avatud")),
                (
                    "warning_codes",
                    models.JSONField(blank=True, default=list, verbose_name="Hoiatuskoodid"),
                ),
                ("source_row", models.PositiveIntegerField(verbose_name="Lähterida")),
                (
                    "refreshed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Värskendatud"),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="legal_work.legalworksnapshot",
                        verbose_name="Hetkeseis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Õigusloome kirje",
                "verbose_name_plural": "Õigusloome kirjed",
                "ordering": ("-received_date", "topic", "record_id"),
            },
        ),
        migrations.CreateModel(
            name="LegalWorkFeedState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "last_checked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Viimati kontrollitud"
                    ),
                ),
                (
                    "last_successful_sync_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Viimane edukas sünkroonimine"
                    ),
                ),
                (
                    "last_changed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Viimati muutunud"),
                ),
                (
                    "last_result",
                    models.CharField(
                        choices=[
                            ("never_run", "Pole veel käivitatud"),
                            ("imported", "Imporditud"),
                            ("unchanged", "Muutumatu"),
                            ("failed", "Ebaõnnestus"),
                        ],
                        default="never_run",
                        max_length=16,
                        verbose_name="Viimane tulemus",
                    ),
                ),
                (
                    "last_error_summary",
                    models.CharField(
                        blank=True,
                        help_text="Puhastatud ja lühendatud. Ei sisalda tokeneid ega failisisu.",
                        max_length=500,
                        verbose_name="Viimane veateade",
                    ),
                ),
                (
                    "remote_modified_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Kaugfail muudetud"),
                ),
                (
                    "remote_etag",
                    models.CharField(blank=True, max_length=200, verbose_name="Kaugfaili etag"),
                ),
                (
                    "remote_size_bytes",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="Kaugfaili suurus"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Muudetud")),
                (
                    "source",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legal_work_feed_state",
                        to="sources.datasource",
                        verbose_name="Andmeallikas",
                    ),
                ),
                (
                    "current_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="legal_work.legalworksnapshot",
                        verbose_name="Kehtiv hetkeseis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Õigusloome andmevoo olek",
                "verbose_name_plural": "Õigusloome andmevoo olekud",
            },
        ),
        migrations.AddConstraint(
            model_name="legalworksnapshot",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("source",),
                name="legalwork_one_current_snapshot_per_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="legalworksnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(("open_record_count__lte", models.F("total_record_count"))),
                name="legalwork_open_count_within_total",
            ),
        ),
        migrations.AddConstraint(
            model_name="legalworksnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(("sent_record_count__lte", models.F("total_record_count"))),
                name="legalwork_sent_count_within_total",
            ),
        ),
        migrations.AddConstraint(
            model_name="legalworksnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(("warning_record_count__lte", models.F("total_record_count"))),
                name="legalwork_warning_count_within_total",
            ),
        ),
        migrations.AddIndex(
            model_name="legalworkitem",
            index=models.Index(
                fields=["snapshot", "is_open"], name="legal_work__snapsho_21f430_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="legalworkitem",
            index=models.Index(
                fields=["snapshot", "-sent_date"], name="legal_work__snapsho_69fb3e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="legalworkitem",
            index=models.Index(
                fields=["snapshot", "-received_date"], name="legal_work__snapsho_1faaa2_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="legalworkitem",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "record_id"), name="legalworkitem_unique_record_per_snapshot"
            ),
        ),
        migrations.AddConstraint(
            model_name="legalworkitem",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "source_year", "source_row"),
                name="legalworkitem_unique_source_row_per_snapshot",
            ),
        ),
        migrations.AddConstraint(
            model_name="legalworkitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("source_year__gte", 1)),
                name="legalworkitem_source_year_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="legalworkitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("source_nr__isnull", True), ("source_nr__gte", 0), _connector="OR"
                ),
                name="legalworkitem_source_nr_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="legalworkitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("topic", ""), _negated=True),
                name="legalworkitem_topic_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="legalworkitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("sent_date__isnull", False), ("sent_status", "sent")),
                    models.Q(
                        models.Q(("sent_status", "sent"), _negated=True),
                        ("sent_date__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="legalworkitem_sent_date_matches_status",
            ),
        ),
    ]
