# Generated by Django 5.2.16 on 2026-08-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("legal_work", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="legalworkitem",
            name="feedback_member_count",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Tagasisidet andnud liikmeid"
            ),
        ),
        migrations.AddField(
            model_name="legalworkitem",
            name="feedback_requested_member_count",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Liikmeid, kellelt otse küsiti"
            ),
        ),
    ]
