# Generated by Django 5.2.16 on 2026-08-05 17:46

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("legal_work", "0002_legalworkitem_feedback_member_count_and_more"),
        ("sources", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CurrentTopicSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("observed_at", models.DateTimeField(verbose_name="Kogutud")),
                ("item_count", models.PositiveIntegerField(default=0, verbose_name="Teemasid")),
                ("is_current", models.BooleanField(default=False, verbose_name="Kehtiv")),
                (
                    "artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="current_topic_snapshots",
                        to="sources.sourceartifact",
                        verbose_name="Algfail",
                    ),
                ),
                (
                    "import_run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="current_topic_snapshot",
                        to="sources.importrun",
                        verbose_name="Impordikäivitus",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="current_topic_snapshots",
                        to="sources.datasource",
                        verbose_name="Andmeallikas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Koda.ee hetkel käsil hetkeseis",
                "verbose_name_plural": "Koda.ee hetkel käsil hetkeseisud",
                "ordering": ("-observed_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="CurrentTopicItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("content_key", models.CharField(max_length=64, verbose_name="Sisu võti")),
                ("canonical_url", models.URLField(max_length=500, verbose_name="Aadress")),
                ("title", models.CharField(max_length=500, verbose_name="Pealkiri")),
                ("listing_summary", models.TextField(blank=True, verbose_name="Loendi kokkuvõte")),
                ("body_text", models.TextField(blank=True, verbose_name="Lehe tekst")),
                (
                    "published_date",
                    models.DateField(blank=True, null=True, verbose_name="Avaldatud"),
                ),
                (
                    "feedback_deadline",
                    models.DateField(blank=True, null=True, verbose_name="Tagasiside tähtaeg"),
                ),
                (
                    "named_organization",
                    models.CharField(blank=True, max_length=200, verbose_name="Nimetatud asutus"),
                ),
                ("source_order", models.PositiveSmallIntegerField(verbose_name="Järjekord")),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="legal_work.currenttopicsnapshot",
                        verbose_name="Hetkeseis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Koda.ee hetkel käsil teema",
                "verbose_name_plural": "Koda.ee hetkel käsil teemad",
                "ordering": ("snapshot", "source_order"),
            },
        ),
        migrations.CreateModel(
            name="CurrentTopicFeedState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "last_checked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Viimati kontrollitud"
                    ),
                ),
                (
                    "last_successful_sync_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Viimane edukas sünkroonimine"
                    ),
                ),
                (
                    "last_changed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Viimati muutunud"),
                ),
                (
                    "last_result",
                    models.CharField(
                        choices=[
                            ("never_run", "Pole veel käivitatud"),
                            ("imported", "Imporditud"),
                            ("unchanged", "Muutumatu"),
                            ("failed", "Ebaõnnestus"),
                        ],
                        default="never_run",
                        max_length=16,
                        verbose_name="Viimane tulemus",
                    ),
                ),
                (
                    "last_error_summary",
                    models.CharField(
                        blank=True,
                        help_text="Puhastatud ja lühendatud. Ei sisalda lehe sisu ega aadresse.",
                        max_length=500,
                        verbose_name="Viimane veateade",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Muudetud")),
                (
                    "source",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="current_topic_feed_state",
                        to="sources.datasource",
                        verbose_name="Andmeallikas",
                    ),
                ),
                (
                    "current_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="legal_work.currenttopicsnapshot",
                        verbose_name="Kehtiv hetkeseis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hetkel käsil andmevoo olek",
                "verbose_name_plural": "Hetkel käsil andmevoo olekud",
            },
        ),
        migrations.CreateModel(
            name="LegalCurrentTopicMatchSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "matcher_version",
                    models.CharField(max_length=32, verbose_name="Sobitaja versioon"),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True, verbose_name="Arvutatud")),
                (
                    "legal_item_count",
                    models.PositiveIntegerField(default=0, verbose_name="Avatud kirjeid"),
                ),
                ("matched_count", models.PositiveIntegerField(default=0, verbose_name="Seotud")),
                (
                    "ambiguous_count",
                    models.PositiveIntegerField(default=0, verbose_name="Ebaselgeid"),
                ),
                (
                    "unmatched_count",
                    models.PositiveIntegerField(default=0, verbose_name="Sidumata"),
                ),
                ("is_current", models.BooleanField(default=False, verbose_name="Kehtiv")),
                (
                    "current_topic_snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_snapshots",
                        to="legal_work.currenttopicsnapshot",
                        verbose_name="Hetkel käsil hetkeseis",
                    ),
                ),
                (
                    "legal_snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="current_topic_match_snapshots",
                        to="legal_work.legalworksnapshot",
                        verbose_name="Õigusloome hetkeseis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Õigusloome sobitamise hetkeseis",
                "verbose_name_plural": "Õigusloome sobitamise hetkeseisud",
                "ordering": ("-generated_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="LegalCurrentTopicMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("matched", "Seotud"),
                            ("ambiguous", "Ebaselge"),
                            ("unmatched", "Sidumata"),
                        ],
                        db_index=True,
                        max_length=16,
                        verbose_name="Otsus",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(decimal_places=2, max_digits=5, verbose_name="Skoor"),
                ),
                (
                    "runner_up_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="0 kui teist kandidaati ei olnud.",
                        max_digits=5,
                        verbose_name="Teise koha skoor",
                    ),
                ),
                (
                    "score_margin",
                    models.DecimalField(decimal_places=2, max_digits=5, verbose_name="Vahe"),
                ),
                (
                    "candidate_count",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Kandidaate"),
                ),
                (
                    "evidence_codes",
                    models.JSONField(blank=True, default=list, verbose_name="Tõendikoodid"),
                ),
                (
                    "best_candidate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="legal_work.currenttopicitem",
                        verbose_name="Parim kandidaat",
                    ),
                ),
                (
                    "legal_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="legal_work.legalworkitem",
                        verbose_name="Õigusloome kirje",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="legal_work.legalcurrenttopicmatchsnapshot",
                        verbose_name="Sobitamise hetkeseis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Õigusloome sobitamise tulemus",
                "verbose_name_plural": "Õigusloome sobitamise tulemused",
                "ordering": ("-score", "legal_item_id"),
            },
        ),
        migrations.AddConstraint(
            model_name="currenttopicsnapshot",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("source",),
                name="currenttopic_one_current_snapshot_per_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="currenttopicitem",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "content_key"), name="currenttopicitem_unique_key_per_snapshot"
            ),
        ),
        migrations.AddConstraint(
            model_name="currenttopicitem",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "canonical_url"),
                name="currenttopicitem_unique_url_per_snapshot",
            ),
        ),
        migrations.AddConstraint(
            model_name="currenttopicitem",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "source_order"),
                name="currenttopicitem_unique_order_per_snapshot",
            ),
        ),
        migrations.AddConstraint(
            model_name="currenttopicitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("title", ""), _negated=True),
                name="currenttopicitem_title_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="currenttopicitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("canonical_url", ""), _negated=True),
                name="currenttopicitem_url_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="legalcurrenttopicmatchsnapshot",
            constraint=models.UniqueConstraint(
                fields=("legal_snapshot", "current_topic_snapshot", "matcher_version"),
                name="legalmatchsnapshot_unique_inputs",
            ),
        ),
        migrations.AddConstraint(
            model_name="legalcurrenttopicmatchsnapshot",
            constraint=models.UniqueConstraint(
                models.F("is_current"),
                condition=models.Q(("is_current", True)),
                name="legalmatchsnapshot_one_current",
            ),
        ),
        migrations.AddConstraint(
            model_name="legalcurrenttopicmatchsnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(("matched_count__lte", models.F("legal_item_count"))),
                name="legalmatchsnapshot_matched_within_total",
            ),
        ),
        migrations.AddConstraint(
            model_name="legalcurrenttopicmatchsnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(("ambiguous_count__lte", models.F("legal_item_count"))),
                name="legalmatchsnapshot_ambiguous_within_total",
            ),
        ),
        migrations.AddConstraint(
            model_name="legalcurrenttopicmatchsnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(("unmatched_count__lte", models.F("legal_item_count"))),
                name="legalmatchsnapshot_unmatched_within_total",
            ),
        ),
        migrations.AddIndex(
            model_name="legalcurrenttopicmatch",
            index=models.Index(
                fields=["snapshot", "decision"], name="legal_work__snapsho_892da3_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="legalcurrenttopicmatch",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "legal_item"), name="legalmatch_one_decision_per_item"
            ),
        ),
        migrations.AddConstraint(
            model_name="legalcurrenttopicmatch",
            constraint=models.CheckConstraint(
                condition=models.Q(("score__gte", 0), ("score__lte", 100)),
                name="legalmatch_score_within_scale",
            ),
        ),
        migrations.AddConstraint(
            model_name="legalcurrenttopicmatch",
            constraint=models.CheckConstraint(
                condition=models.Q(("runner_up_score__gte", 0), ("runner_up_score__lte", 100)),
                name="legalmatch_runner_up_within_scale",
            ),
        ),
        migrations.AddConstraint(
            model_name="legalcurrenttopicmatch",
            constraint=models.CheckConstraint(
                condition=models.Q(("score__gte", models.F("runner_up_score"))),
                name="legalmatch_runner_up_not_above_score",
            ),
        ),
        migrations.AddConstraint(
            model_name="legalcurrenttopicmatch",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "score_margin",
                        django.db.models.expressions.CombinedExpression(
                            models.F("score"), "-", models.F("runner_up_score")
                        ),
                    )
                ),
                name="legalmatch_margin_is_score_difference",
            ),
        ),
        migrations.AddConstraint(
            model_name="legalcurrenttopicmatch",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("decision", "matched"), _negated=True),
                    ("best_candidate__isnull", False),
                    _connector="OR",
                ),
                name="legalmatch_matched_requires_candidate",
            ),
        ),
    ]
