# Generated by Django 5.2.16 on 2026-08-06 07:42

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_work', '0003_current_topic_catalogue_and_matching'),
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedTopicSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_at', models.DateTimeField(verbose_name='Kogutud')),
                ('item_count', models.PositiveIntegerField(default=0, verbose_name='Kirjeid indeksis')),
                ('detailed_item_count', models.PositiveIntegerField(default=0, verbose_name='Loetud lehti')),
                ('pending_detail_count', models.PositiveIntegerField(default=0, verbose_name='Lugemata lehti')),
                ('failed_detail_count', models.PositiveIntegerField(default=0, verbose_name='Ebaõnnestunud lehti')),
                ('pages_fetched', models.PositiveSmallIntegerField(default=0, verbose_name='Loetud loendilehti')),
                ('backfill_complete', models.BooleanField(default=False, verbose_name='Täielik')),
                ('is_current', models.BooleanField(default=False, verbose_name='Kehtiv')),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='archived_topic_snapshots', to='sources.sourceartifact', verbose_name='Algfail')),
                ('import_run', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='archived_topic_snapshot', to='sources.importrun', verbose_name='Impordikäivitus')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='archived_topic_snapshots', to='sources.datasource', verbose_name='Andmeallikas')),
            ],
            options={
                'verbose_name': 'Hetkel käsil arhiivi hetkeseis',
                'verbose_name_plural': 'Hetkel käsil arhiivi hetkeseisud',
                'ordering': ('-observed_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ArchivedTopicItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_key', models.CharField(max_length=64, verbose_name='Sisu võti')),
                ('canonical_url', models.URLField(max_length=500, verbose_name='Aadress')),
                ('title', models.CharField(max_length=500, verbose_name='Loendi pealkiri')),
                ('listing_summary', models.TextField(blank=True, verbose_name='Loendi kokkuvõte')),
                ('source_page', models.PositiveSmallIntegerField(default=0, verbose_name='Loendileht')),
                ('source_order', models.PositiveIntegerField(verbose_name='Järjekord')),
                ('is_present', models.BooleanField(default=True, verbose_name='Arhiivis olemas')),
                ('detail_status', models.CharField(choices=[('pending', 'Ootel'), ('hydrated', 'Loetud'), ('failed', 'Ebaõnnestus')], db_index=True, default='pending', max_length=16, verbose_name='Lehe olek')),
                ('detail_title', models.CharField(blank=True, max_length=500, verbose_name='Lehe pealkiri')),
                ('body_text', models.TextField(blank=True, verbose_name='Lehe tekst')),
                ('published_date', models.DateField(blank=True, null=True, verbose_name='Avaldatud')),
                ('feedback_deadline', models.DateField(blank=True, null=True, verbose_name='Tagasiside tähtaeg')),
                ('named_organization', models.CharField(blank=True, max_length=200, verbose_name='Nimetatud asutus')),
                ('detail_content_hash', models.CharField(blank=True, max_length=64, verbose_name='Lehe räsi')),
                ('detail_fetched_at', models.DateTimeField(blank=True, null=True, verbose_name='Leht loetud')),
                ('detail_failure_code', models.CharField(blank=True, max_length=32, verbose_name='Vea kood')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='legal_work.archivedtopicsnapshot', verbose_name='Hetkeseis')),
            ],
            options={
                'verbose_name': 'Hetkel käsil arhiivi teema',
                'verbose_name_plural': 'Hetkel käsil arhiivi teemad',
                'ordering': ('snapshot', 'source_order'),
            },
        ),
        migrations.CreateModel(
            name='ArchivedTopicFeedState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='Viimati kontrollitud')),
                ('last_successful_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Viimane edukas sünkroonimine')),
                ('last_changed_at', models.DateTimeField(blank=True, null=True, verbose_name='Viimati muutunud')),
                ('last_result', models.CharField(choices=[('never_run', 'Pole veel käivitatud'), ('imported', 'Imporditud'), ('unchanged', 'Muutumatu'), ('failed', 'Ebaõnnestus')], default='never_run', max_length=16, verbose_name='Viimane tulemus')),
                ('last_error_summary', models.CharField(blank=True, help_text='Puhastatud ja lühendatud. Ei sisalda lehe sisu ega aadresse.', max_length=500, verbose_name='Viimane veateade')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Muudetud')),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='archived_topic_feed_state', to='sources.datasource', verbose_name='Andmeallikas')),
                ('current_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='legal_work.archivedtopicsnapshot', verbose_name='Kehtiv hetkeseis')),
            ],
            options={
                'verbose_name': 'Arhiivi andmevoo olek',
                'verbose_name_plural': 'Arhiivi andmevoo olekud',
            },
        ),
        migrations.CreateModel(
            name='LegalArchivedTopicMatchSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matcher_version', models.CharField(max_length=48, verbose_name='Sobitaja versioon')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Arvutatud')),
                ('considered_item_count', models.PositiveIntegerField(default=0, verbose_name='Vaadatud kirjeid')),
                ('matched_count', models.PositiveIntegerField(default=0, verbose_name='Seotud')),
                ('ambiguous_count', models.PositiveIntegerField(default=0, verbose_name='Ebaselgeid')),
                ('unmatched_count', models.PositiveIntegerField(default=0, verbose_name='Sidumata')),
                ('is_current', models.BooleanField(default=False, verbose_name='Kehtiv')),
                ('archived_topic_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_snapshots', to='legal_work.archivedtopicsnapshot', verbose_name='Arhiivi hetkeseis')),
                ('current_topic_match_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive_fallback_snapshots', to='legal_work.legalcurrenttopicmatchsnapshot', verbose_name='Hetkel käsil sobitamine')),
                ('legal_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_topic_match_snapshots', to='legal_work.legalworksnapshot', verbose_name='Õigusloome hetkeseis')),
            ],
            options={
                'verbose_name': 'Arhiivi sobitamise hetkeseis',
                'verbose_name_plural': 'Arhiivi sobitamise hetkeseisud',
                'ordering': ('-generated_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='LegalArchivedTopicMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('matched', 'Seotud'), ('ambiguous', 'Ebaselge'), ('unmatched', 'Sidumata')], db_index=True, max_length=16, verbose_name='Otsus')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Skoor')),
                ('runner_up_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Teise koha skoor')),
                ('score_margin', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Vahe')),
                ('candidate_count', models.PositiveSmallIntegerField(default=0, verbose_name='Kandidaate')),
                ('evidence_codes', models.JSONField(blank=True, default=list, verbose_name='Tõendikoodid')),
                ('best_candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='legal_work.archivedtopicitem', verbose_name='Parim kandidaat')),
                ('legal_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='legal_work.legalworkitem', verbose_name='Õigusloome kirje')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='legal_work.legalarchivedtopicmatchsnapshot', verbose_name='Sobitamise hetkeseis')),
            ],
            options={
                'verbose_name': 'Arhiivi sobitamise tulemus',
                'verbose_name_plural': 'Arhiivi sobitamise tulemused',
                'ordering': ('-score', 'legal_item_id'),
            },
        ),
        migrations.AddConstraint(
            model_name='archivedtopicsnapshot',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('source',), name='archivedtopic_one_current_snapshot_per_source'),
        ),
        migrations.AddConstraint(
            model_name='archivedtopicsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('detailed_item_count__lte', models.F('item_count'))), name='archivedtopic_detailed_within_total'),
        ),
        migrations.AddIndex(
            model_name='archivedtopicitem',
            index=models.Index(fields=['snapshot', 'detail_status'], name='legal_work__snapsho_00edf6_idx'),
        ),
        migrations.AddIndex(
            model_name='archivedtopicitem',
            index=models.Index(fields=['snapshot', 'source_page'], name='legal_work__snapsho_780c5f_idx'),
        ),
        migrations.AddConstraint(
            model_name='archivedtopicitem',
            constraint=models.UniqueConstraint(fields=('snapshot', 'content_key'), name='archivedtopicitem_unique_key_per_snapshot'),
        ),
        migrations.AddConstraint(
            model_name='archivedtopicitem',
            constraint=models.UniqueConstraint(fields=('snapshot', 'canonical_url'), name='archivedtopicitem_unique_url_per_snapshot'),
        ),
        migrations.AddConstraint(
            model_name='archivedtopicitem',
            constraint=models.CheckConstraint(condition=models.Q(('title', ''), _negated=True), name='archivedtopicitem_title_required'),
        ),
        migrations.AddConstraint(
            model_name='archivedtopicitem',
            constraint=models.CheckConstraint(condition=models.Q(('canonical_url', ''), _negated=True), name='archivedtopicitem_url_required'),
        ),
        migrations.AddConstraint(
            model_name='archivedtopicitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('detail_status', 'hydrated'), _negated=True), models.Q(('body_text', ''), _negated=True), _connector='OR'), name='archivedtopicitem_hydrated_has_body'),
        ),
        migrations.AddConstraint(
            model_name='legalarchivedtopicmatchsnapshot',
            constraint=models.UniqueConstraint(fields=('legal_snapshot', 'archived_topic_snapshot', 'current_topic_match_snapshot', 'matcher_version'), name='legalarchivematch_unique_inputs'),
        ),
        migrations.AddConstraint(
            model_name='legalarchivedtopicmatchsnapshot',
            constraint=models.UniqueConstraint(models.F('is_current'), condition=models.Q(('is_current', True)), name='legalarchivematch_one_current'),
        ),
        migrations.AddConstraint(
            model_name='legalarchivedtopicmatchsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('matched_count__lte', models.F('considered_item_count'))), name='legalarchivematch_matched_within_total'),
        ),
        migrations.AddIndex(
            model_name='legalarchivedtopicmatch',
            index=models.Index(fields=['snapshot', 'decision'], name='legal_work__snapsho_c5a485_idx'),
        ),
        migrations.AddConstraint(
            model_name='legalarchivedtopicmatch',
            constraint=models.UniqueConstraint(fields=('snapshot', 'legal_item'), name='legalarchivematch_one_decision_per_item'),
        ),
        migrations.AddConstraint(
            model_name='legalarchivedtopicmatch',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 0), ('score__lte', 100)), name='legalarchivematch_score_within_scale'),
        ),
        migrations.AddConstraint(
            model_name='legalarchivedtopicmatch',
            constraint=models.CheckConstraint(condition=models.Q(('runner_up_score__gte', 0), ('runner_up_score__lte', 100)), name='legalarchivematch_runner_up_within_scale'),
        ),
        migrations.AddConstraint(
            model_name='legalarchivedtopicmatch',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', models.F('runner_up_score'))), name='legalarchivematch_runner_up_not_above_score'),
        ),
        migrations.AddConstraint(
            model_name='legalarchivedtopicmatch',
            constraint=models.CheckConstraint(condition=models.Q(('score_margin', django.db.models.expressions.CombinedExpression(models.F('score'), '-', models.F('runner_up_score')))), name='legalarchivematch_margin_is_score_difference'),
        ),
        migrations.AddConstraint(
            model_name='legalarchivedtopicmatch',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('decision', 'matched'), _negated=True), ('best_candidate__isnull', False), _connector='OR'), name='legalarchivematch_matched_requires_candidate'),
        ),
    ]
