# Generated by Django 5.2.16 on 2026-08-06 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("legal_work", "0004_archived_topic_catalogue_and_matching"),
        ("sources", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpinionCatalogueSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "source_manifest_checksum",
                    models.CharField(max_length=64, verbose_name="Lähtekomplekti räsi"),
                ),
                (
                    "extractor_version",
                    models.CharField(max_length=20, verbose_name="Lugeja versioon"),
                ),
                ("observed_at", models.DateTimeField(verbose_name="Kogutud")),
                ("entry_count", models.PositiveIntegerField(default=0, verbose_name="Kirjeid")),
                ("valid_count", models.PositiveIntegerField(default=0, verbose_name="Korras")),
                (
                    "quarantined_count",
                    models.PositiveIntegerField(default=0, verbose_name="Karantiinis"),
                ),
                ("extracted_count", models.PositiveIntegerField(default=0, verbose_name="Loetud")),
                (
                    "needs_ocr_count",
                    models.PositiveIntegerField(default=0, verbose_name="Vajab OCR-i"),
                ),
                (
                    "failed_extraction_count",
                    models.PositiveIntegerField(default=0, verbose_name="Lugemata"),
                ),
                ("is_current", models.BooleanField(default=False, verbose_name="Kehtiv")),
                (
                    "artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="opinion_catalogue_snapshots",
                        to="sources.sourceartifact",
                        verbose_name="Algfail",
                    ),
                ),
                (
                    "import_run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="opinion_catalogue_snapshot",
                        to="sources.importrun",
                        verbose_name="Impordikäivitus",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="opinion_catalogue_snapshots",
                        to="sources.datasource",
                        verbose_name="Andmeallikas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Arvamuste kataloogi hetkeseis",
                "verbose_name_plural": "Arvamuste kataloogi hetkeseisud",
                "ordering": ("-observed_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="OpinionCatalogueFeedState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "last_checked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Viimati kontrollitud"
                    ),
                ),
                (
                    "last_successful_sync_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Viimane edukas sünkroonimine"
                    ),
                ),
                (
                    "last_changed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Viimati muutunud"),
                ),
                (
                    "last_result",
                    models.CharField(
                        choices=[
                            ("never_run", "Pole veel käivitatud"),
                            ("imported", "Imporditud"),
                            ("unchanged", "Muutumatu"),
                            ("partial", "Osaliselt töödeldud"),
                            ("failed", "Ebaõnnestus"),
                        ],
                        default="never_run",
                        max_length=16,
                        verbose_name="Viimane tulemus",
                    ),
                ),
                (
                    "last_error_summary",
                    models.CharField(
                        blank=True,
                        help_text="Puhastatud ja lühendatud. Ei sisalda failinimesid ega teid.",
                        max_length=500,
                        verbose_name="Viimane veateade",
                    ),
                ),
                (
                    "build_state",
                    models.CharField(
                        choices=[
                            ("idle", "Ootel"),
                            ("building", "Töös"),
                            ("complete", "Valmis"),
                            ("failed", "Ebaõnnestus"),
                        ],
                        default="idle",
                        max_length=16,
                        verbose_name="Ehituse olek",
                    ),
                ),
                (
                    "building_manifest_checksum",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Töös oleva komplekti räsi"
                    ),
                ),
                (
                    "manifest_entry_count",
                    models.PositiveIntegerField(default=0, verbose_name="Kirjeid kokku"),
                ),
                (
                    "processed_entry_count",
                    models.PositiveIntegerField(default=0, verbose_name="Töödeldud"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Muudetud")),
                (
                    "source",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="opinion_catalogue_feed_state",
                        to="sources.datasource",
                        verbose_name="Andmeallikas",
                    ),
                ),
                (
                    "current_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="legal_work.opinioncataloguesnapshot",
                        verbose_name="Kehtiv hetkeseis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Arvamuste andmevoo olek",
                "verbose_name_plural": "Arvamuste andmevoo olekud",
            },
        ),
        migrations.CreateModel(
            name="OpinionDocumentBlob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sha256", models.CharField(max_length=64, unique=True, verbose_name="SHA-256")),
                ("storage_key", models.CharField(max_length=120, verbose_name="Hoiuvõti")),
                ("byte_size", models.PositiveIntegerField(verbose_name="Suurus baitides")),
                (
                    "page_count",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Lehekülgi"),
                ),
                (
                    "validation_status",
                    models.CharField(
                        choices=[
                            ("valid", "Korras"),
                            ("quarantined_encrypted", "Karantiin: krüpteeritud"),
                            ("quarantined_active_content", "Karantiin: aktiivne sisu"),
                            ("quarantined_invalid", "Karantiin: vigane fail"),
                            ("quarantined_too_large", "Karantiin: liiga suur"),
                            ("quarantined_too_many_pages", "Karantiin: liiga palju lehti"),
                        ],
                        db_index=True,
                        max_length=32,
                        verbose_name="Kontrolli tulemus",
                    ),
                ),
                ("is_encrypted", models.BooleanField(default=False, verbose_name="Krüpteeritud")),
                (
                    "has_active_content",
                    models.BooleanField(default=False, verbose_name="Aktiivne sisu"),
                ),
                (
                    "warning_codes",
                    models.JSONField(blank=True, default=list, verbose_name="Hoiatuskoodid"),
                ),
                ("imported_at", models.DateTimeField(auto_now_add=True, verbose_name="Lisatud")),
            ],
            options={
                "verbose_name": "Arvamusdokumendi fail",
                "verbose_name_plural": "Arvamusdokumentide failid",
                "ordering": ("-imported_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["validation_status", "imported_at"],
                        name="legal_work__validat_6e1007_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("sha256__regex", "^[0-9a-f]{64}$")),
                        name="opinionblob_sha256_is_lower_hex",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("byte_size__gt", 0)), name="opinionblob_has_bytes"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("validation_status", "valid"), _negated=True),
                            ("page_count__gt", 0),
                            _connector="OR",
                        ),
                        name="opinionblob_valid_has_pages",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("validation_status", "valid"), _negated=True),
                            ("has_active_content", False),
                            _connector="OR",
                        ),
                        name="opinionblob_valid_has_no_active_content",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OpinionDocumentExtraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("extractor_name", models.CharField(max_length=40, verbose_name="Lugeja")),
                (
                    "extractor_version",
                    models.CharField(max_length=20, verbose_name="Lugeja versioon"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("extracted", "Loetud"),
                            ("needs_ocr", "Vajab OCR-i"),
                            ("failed", "Ebaõnnestus"),
                        ],
                        db_index=True,
                        max_length=16,
                        verbose_name="Olek",
                    ),
                ),
                ("text", models.TextField(blank=True, verbose_name="Tekst")),
                ("first_page_text", models.TextField(blank=True, verbose_name="Esilehe tekst")),
                (
                    "text_sha256",
                    models.CharField(blank=True, max_length=64, verbose_name="Teksti räsi"),
                ),
                (
                    "page_count",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Lehekülgi"),
                ),
                (
                    "detected_date",
                    models.DateField(blank=True, null=True, verbose_name="Kirja kuupäev"),
                ),
                (
                    "detected_recipient",
                    models.CharField(blank=True, max_length=200, verbose_name="Kirja saaja"),
                ),
                (
                    "detected_subject",
                    models.CharField(blank=True, max_length=500, verbose_name="Kirja teema"),
                ),
                (
                    "detected_reference",
                    models.CharField(blank=True, max_length=100, verbose_name="Väljamineku number"),
                ),
                (
                    "their_reference",
                    models.CharField(blank=True, max_length=100, verbose_name="Teie viide"),
                ),
                (
                    "our_reference",
                    models.CharField(blank=True, max_length=100, verbose_name="Meie viide"),
                ),
                (
                    "warning_codes",
                    models.JSONField(blank=True, default=list, verbose_name="Hoiatuskoodid"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Loodud")),
                (
                    "blob",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extractions",
                        to="legal_work.opiniondocumentblob",
                        verbose_name="Fail",
                    ),
                ),
            ],
            options={
                "verbose_name": "Arvamusdokumendi lugemine",
                "verbose_name_plural": "Arvamusdokumentide lugemised",
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="OpinionCatalogueEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "source_provider",
                    models.CharField(
                        choices=[("bootstrap_zip", "Algarhiiv"), ("directory", "Kaust")],
                        max_length=20,
                        verbose_name="Lähteliik",
                    ),
                ),
                (
                    "source_entry_key",
                    models.CharField(max_length=400, verbose_name="Lähtekirje võti"),
                ),
                (
                    "original_filename",
                    models.CharField(max_length=400, verbose_name="Algne failinimi"),
                ),
                (
                    "display_filename",
                    models.CharField(max_length=400, verbose_name="Kuvatav failinimi"),
                ),
                (
                    "filename_date",
                    models.DateField(blank=True, null=True, verbose_name="Nimest kuupäev"),
                ),
                (
                    "filename_recipient",
                    models.CharField(blank=True, max_length=200, verbose_name="Nimest saaja"),
                ),
                (
                    "filename_subject",
                    models.CharField(blank=True, max_length=500, verbose_name="Nimest teema"),
                ),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("opinion", "Arvamus"),
                            ("joint_opinion", "Ühisarvamus"),
                            ("supplementary_opinion", "Täiendav arvamus"),
                            ("follow_up", "Järelkiri"),
                            ("annex", "Lisa"),
                            ("supporting_document", "Tugidokument"),
                            ("unknown", "Määramata"),
                        ],
                        db_index=True,
                        default="unknown",
                        max_length=32,
                        verbose_name="Liik",
                    ),
                ),
                (
                    "classification_signals",
                    models.JSONField(blank=True, default=list, verbose_name="Liigituse tunnused"),
                ),
                ("source_order", models.PositiveIntegerField(verbose_name="Järjekord")),
                (
                    "warning_codes",
                    models.JSONField(blank=True, default=list, verbose_name="Hoiatuskoodid"),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="legal_work.opinioncataloguesnapshot",
                        verbose_name="Hetkeseis",
                    ),
                ),
                (
                    "blob",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="catalogue_entries",
                        to="legal_work.opiniondocumentblob",
                        verbose_name="Fail",
                    ),
                ),
                (
                    "extraction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="catalogue_entries",
                        to="legal_work.opiniondocumentextraction",
                        verbose_name="Lugemine",
                    ),
                ),
            ],
            options={
                "verbose_name": "Arvamuste kataloogi kirje",
                "verbose_name_plural": "Arvamuste kataloogi kirjed",
                "ordering": ("snapshot", "source_order"),
            },
        ),
        migrations.AddConstraint(
            model_name="opinioncataloguesnapshot",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("source",),
                name="opinioncatalogue_one_current_per_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="opinioncataloguesnapshot",
            constraint=models.UniqueConstraint(
                fields=("source", "source_manifest_checksum", "extractor_version"),
                name="opinioncatalogue_unique_manifest_and_extractor",
            ),
        ),
        migrations.AddConstraint(
            model_name="opinioncataloguesnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(("valid_count__lte", models.F("entry_count"))),
                name="opinioncatalogue_valid_within_total",
            ),
        ),
        migrations.AddConstraint(
            model_name="opinioncataloguesnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(("quarantined_count__lte", models.F("entry_count"))),
                name="opinioncatalogue_quarantined_within_total",
            ),
        ),
        migrations.AddConstraint(
            model_name="opinioncataloguesnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(("extracted_count__lte", models.F("valid_count"))),
                name="opinioncatalogue_extracted_within_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="opinioncataloguefeedstate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("processed_entry_count__lte", models.F("manifest_entry_count"))
                ),
                name="opinionfeedstate_processed_within_manifest",
            ),
        ),
        migrations.AddIndex(
            model_name="opiniondocumentextraction",
            index=models.Index(
                fields=["status", "extractor_version"], name="legal_work__status_c2bee9_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="opiniondocumentextraction",
            constraint=models.UniqueConstraint(
                fields=("blob", "extractor_version"),
                name="opinionextraction_one_per_blob_and_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="opiniondocumentextraction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "extracted"), _negated=True),
                    models.Q(("text", ""), _negated=True),
                    _connector="OR",
                ),
                name="opinionextraction_extracted_has_text",
            ),
        ),
        migrations.AddIndex(
            model_name="opinioncatalogueentry",
            index=models.Index(
                fields=["snapshot", "classification"], name="legal_work__snapsho_798293_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="opinioncatalogueentry",
            index=models.Index(
                fields=["snapshot", "filename_date"], name="legal_work__snapsho_5247f3_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="opinioncatalogueentry",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "source_entry_key"),
                name="opinionentry_unique_source_key_per_snapshot",
            ),
        ),
        migrations.AddConstraint(
            model_name="opinioncatalogueentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("original_filename", ""), _negated=True),
                name="opinionentry_filename_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="opinioncatalogueentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("extraction__isnull", True), ("blob__isnull", False), _connector="OR"
                ),
                name="opinionentry_extraction_requires_blob",
            ),
        ),
    ]
