# Generated by Django 5.2.16 on 2026-08-06 22:53

import uuid

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


def _assign_blob_public_ids(apps, schema_editor):
    """Give every existing blob its own opaque identifier.

    Batched rather than one query per row: the pilot catalogue is 34 documents
    but the full handover is 759, and a migration that scales with the table is
    the kind that times out on the one deployment that matters.
    """
    Blob = apps.get_model("legal_work", "OpinionDocumentBlob")
    batch = []
    for blob in Blob.objects.filter(public_id__isnull=True).iterator(chunk_size=500):
        blob.public_id = uuid.uuid4()
        batch.append(blob)
        if len(batch) >= 500:
            Blob.objects.bulk_update(batch, ["public_id"])
            batch.clear()
    if batch:
        Blob.objects.bulk_update(batch, ["public_id"])


class Migration(migrations.Migration):
    dependencies = [
        ("legal_work", "0005_opinion_document_catalogue"),
    ]

    operations = [
        # A unique field with a callable default cannot be added in one step to
        # a table that already holds rows: every existing row would receive the
        # *same* value and the unique index would fail. Add it nullable, give
        # each row its own identifier, then tighten — the documented pattern.
        #
        # The default is deliberately absent here. Keeping `default=uuid.uuid4`
        # on this step defeats the whole pattern: Django evaluates a callable
        # default **once** and writes that single value to every existing row,
        # so the backfill below then finds nothing null and the unique index
        # still fails. Adding the column empty is what makes the backfill the
        # thing that assigns identifiers.
        migrations.AddField(
            model_name="opiniondocumentblob",
            name="public_id",
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.RunPython(
            _assign_blob_public_ids,
            migrations.RunPython.noop,
            elidable=False,
        ),
        migrations.AlterField(
            model_name="opiniondocumentblob",
            name="public_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name="LegalMatter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                (
                    "matter_key",
                    models.CharField(max_length=64, unique=True, verbose_name="Identiteedivõti"),
                ),
                (
                    "identity_version",
                    models.CharField(max_length=8, verbose_name="Identiteedi versioon"),
                ),
                ("last_known_topic", models.TextField(verbose_name="Viimane teadaolev teema")),
                ("received_date", models.DateField(blank=True, null=True, verbose_name="Sisse")),
                (
                    "first_seen_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Esmakordselt nähtud"),
                ),
                (
                    "has_ambiguous_identity",
                    models.BooleanField(default=False, verbose_name="Mitmetähenduslik"),
                ),
            ],
            options={
                "verbose_name": "Õigusloome asi",
                "verbose_name_plural": "Õigusloome asjad",
                "ordering": ("-first_seen_at", "-id"),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("matter_key__regex", "^[0-9a-f]{64}$")),
                        name="legalmatter_key_is_lower_hex",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LegalOpinionMatchSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "matcher_version",
                    models.CharField(max_length=64, verbose_name="Sobitaja versioon"),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True, verbose_name="Arvutatud")),
                (
                    "considered_item_count",
                    models.PositiveIntegerField(default=0, verbose_name="Vaadatud kirjeid"),
                ),
                ("matched_count", models.PositiveIntegerField(default=0, verbose_name="Seotud")),
                (
                    "ambiguous_count",
                    models.PositiveIntegerField(default=0, verbose_name="Ebaselgeid"),
                ),
                (
                    "unmatched_count",
                    models.PositiveIntegerField(default=0, verbose_name="Sidumata"),
                ),
                ("is_current", models.BooleanField(default=False, verbose_name="Kehtiv")),
                (
                    "legal_snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opinion_match_snapshots",
                        to="legal_work.legalworksnapshot",
                        verbose_name="Õigusloome hetkeseis",
                    ),
                ),
                (
                    "opinion_catalogue_snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_snapshots",
                        to="legal_work.opinioncataloguesnapshot",
                        verbose_name="Arvamuste kataloog",
                    ),
                ),
            ],
            options={
                "verbose_name": "Arvamuste sobitamise hetkeseis",
                "verbose_name_plural": "Arvamuste sobitamise hetkeseisud",
                "ordering": ("-generated_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="LegalOpinionDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("matched", "Seotud"),
                            ("ambiguous", "Ebaselge"),
                            ("unmatched", "Sidumata"),
                        ],
                        db_index=True,
                        max_length=16,
                        verbose_name="Otsus",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(decimal_places=2, max_digits=5, verbose_name="Skoor"),
                ),
                (
                    "runner_up_score",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=5, verbose_name="Teise koha skoor"
                    ),
                ),
                (
                    "score_margin",
                    models.DecimalField(decimal_places=2, max_digits=5, verbose_name="Vahe"),
                ),
                (
                    "candidate_count",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Kandidaate"),
                ),
                (
                    "evidence_codes",
                    models.JSONField(blank=True, default=list, verbose_name="Tõendikoodid"),
                ),
                (
                    "contradiction_codes",
                    models.JSONField(blank=True, default=list, verbose_name="Vastuolud"),
                ),
                (
                    "legal_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="legal_work.legalworkitem",
                        verbose_name="Õigusloome kirje",
                    ),
                ),
                (
                    "matter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decisions",
                        to="legal_work.legalmatter",
                        verbose_name="Asi",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisions",
                        to="legal_work.legalopinionmatchsnapshot",
                        verbose_name="Hetkeseis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Arvamuse sobitamise tulemus",
                "verbose_name_plural": "Arvamuse sobitamise tulemused",
                "ordering": ("-score", "legal_item_id"),
            },
        ),
        migrations.CreateModel(
            name="OpinionResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Loodud")),
                (
                    "matter",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resource",
                        to="legal_work.legalmatter",
                        verbose_name="Asi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Arvamuse ressurss",
                "verbose_name_plural": "Arvamuse ressursid",
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="LegalMatterAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("record_id", models.CharField(max_length=64, verbose_name="Kirje ID")),
                ("source_year", models.PositiveSmallIntegerField(verbose_name="Aasta")),
                (
                    "source_nr",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="Number"),
                ),
                ("source_row", models.PositiveIntegerField(verbose_name="Lähterida")),
                ("observed_at", models.DateTimeField(auto_now_add=True, verbose_name="Nähtud")),
                (
                    "matter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="legal_work.legalmatter",
                        verbose_name="Asi",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="legal_work.legalworksnapshot",
                        verbose_name="Hetkeseis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asja varasem tunnus",
                "verbose_name_plural": "Asjade varasemad tunnused",
                "ordering": ("matter", "-snapshot_id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("matter", "snapshot"), name="legalmatteralias_one_per_snapshot"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LegalOpinionDocumentRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("primary", "Põhidokument"),
                            ("joint", "Ühisarvamus"),
                            ("supplementary", "Täiendav"),
                            ("follow_up", "Järelkiri"),
                            ("annex", "Lisa"),
                            ("supporting", "Tugidokument"),
                        ],
                        max_length=16,
                        verbose_name="Roll",
                    ),
                ),
                ("is_primary", models.BooleanField(default=False, verbose_name="Põhidokument")),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=5, verbose_name="Seose skoor"
                    ),
                ),
                (
                    "evidence_codes",
                    models.JSONField(blank=True, default=list, verbose_name="Tõendikoodid"),
                ),
                (
                    "decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relations",
                        to="legal_work.legalopiniondecision",
                        verbose_name="Otsus",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="legal_work.opinioncatalogueentry",
                        verbose_name="Dokument",
                    ),
                ),
            ],
            options={
                "verbose_name": "Arvamuse dokumendiseos",
                "verbose_name_plural": "Arvamuse dokumendiseosed",
                "ordering": ("decision", "-is_primary", "role"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("decision", "entry"),
                        name="legalopinionrelation_unique_entry_per_decision",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_primary", True)),
                        fields=("decision",),
                        name="legalopinionrelation_one_primary_per_decision",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("is_primary", True), _negated=True),
                            ("role", "primary"),
                            _connector="OR",
                        ),
                        name="legalopinionrelation_primary_flag_matches_role",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="legalopinionmatchsnapshot",
            constraint=models.UniqueConstraint(
                fields=("legal_snapshot", "opinion_catalogue_snapshot", "matcher_version"),
                name="legalopinionmatch_unique_inputs",
            ),
        ),
        migrations.AddConstraint(
            model_name="legalopinionmatchsnapshot",
            constraint=models.UniqueConstraint(
                models.F("is_current"),
                condition=models.Q(("is_current", True)),
                name="legalopinionmatch_one_current",
            ),
        ),
        migrations.AddConstraint(
            model_name="legalopinionmatchsnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(("matched_count__lte", models.F("considered_item_count"))),
                name="legalopinionmatch_matched_within_total",
            ),
        ),
        migrations.AddIndex(
            model_name="legalopiniondecision",
            index=models.Index(
                fields=["snapshot", "decision"], name="legal_work__snapsho_b2d1ea_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="legalopiniondecision",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "legal_item"), name="legalopiniondecision_one_per_item"
            ),
        ),
        migrations.AddConstraint(
            model_name="legalopiniondecision",
            constraint=models.CheckConstraint(
                condition=models.Q(("score__gte", 0), ("score__lte", 100)),
                name="legalopiniondecision_score_within_scale",
            ),
        ),
        migrations.AddConstraint(
            model_name="legalopiniondecision",
            constraint=models.CheckConstraint(
                condition=models.Q(("score__gte", models.F("runner_up_score"))),
                name="legalopiniondecision_runner_up_not_above_score",
            ),
        ),
        migrations.AddConstraint(
            model_name="legalopiniondecision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "score_margin",
                        django.db.models.expressions.CombinedExpression(
                            models.F("score"), "-", models.F("runner_up_score")
                        ),
                    )
                ),
                name="legalopiniondecision_margin_is_difference",
            ),
        ),
    ]
