# Generated by Django 5.2.16 on 2026-08-08 07:06
#
# Hand-edited around one transition: `LegalOpinionDocumentRelation` gains its
# document identity directly. The field additions are generated; the backfill
# and the null=False tightening on `blob` are not, and their order matters —
# add nullable, copy the ids up from the entry every existing relation has,
# then require the field. `tests/legal_work/test_opinion_migrations.py` runs
# this against a populated predecessor state.

import django.db.models.deletion
from django.db import migrations, models


def _backfill_relation_documents(apps, schema_editor):
    """Give every existing relation its document identity directly.

    Every historical relation was created from a matchable private entry, so
    the entry always carries a blob and an extraction; copying the two ids up
    makes the relation self-describing before `blob` becomes required.
    """
    Relation = apps.get_model("legal_work", "LegalOpinionDocumentRelation")
    Entry = apps.get_model("legal_work", "OpinionCatalogueEntry")
    Relation.objects.update(
        blob_id=models.Subquery(
            Entry.objects.filter(pk=models.OuterRef("entry_id")).values("blob_id")[:1]
        ),
        extraction_id=models.Subquery(
            Entry.objects.filter(pk=models.OuterRef("entry_id")).values("extraction_id")[:1]
        ),
    )


class Migration(migrations.Migration):
    dependencies = [
        ("legal_work", "0007_catalogue_filename_normaliser_version"),
        ("sources", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalOpinionPageRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=5, verbose_name="Seose skoor"
                    ),
                ),
                (
                    "evidence_codes",
                    models.JSONField(blank=True, default=list, verbose_name="Tõendikoodid"),
                ),
            ],
            options={
                "verbose_name": "Arvamuse leheseos",
                "verbose_name_plural": "Arvamuse leheseosed",
                "ordering": ("decision", "-score"),
            },
        ),
        migrations.CreateModel(
            name="PublicOpinionDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("pdf_url", models.URLField(max_length=500, verbose_name="PDF-i aadress")),
                (
                    "attachment_label",
                    models.CharField(blank=True, max_length=400, verbose_name="Manuse nimi"),
                ),
                (
                    "display_filename",
                    models.CharField(max_length=400, verbose_name="Kuvatav failinimi"),
                ),
                (
                    "filename_date",
                    models.DateField(blank=True, null=True, verbose_name="Nimest kuupäev"),
                ),
                (
                    "filename_recipient",
                    models.CharField(blank=True, max_length=200, verbose_name="Nimest saaja"),
                ),
                (
                    "filename_subject",
                    models.CharField(blank=True, max_length=500, verbose_name="Nimest teema"),
                ),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("opinion", "Arvamus"),
                            ("joint_opinion", "Ühisarvamus"),
                            ("supplementary_opinion", "Täiendav arvamus"),
                            ("follow_up", "Järelkiri"),
                            ("annex", "Lisa"),
                            ("supporting_document", "Tugidokument"),
                            ("unknown", "Määramata"),
                        ],
                        db_index=True,
                        default="unknown",
                        max_length=32,
                        verbose_name="Liik",
                    ),
                ),
                (
                    "classification_signals",
                    models.JSONField(blank=True, default=list, verbose_name="Liigituse tunnused"),
                ),
                (
                    "fetch_state",
                    models.CharField(
                        choices=[
                            ("fetched", "Loetud"),
                            ("carried", "Eelmisest ülekantud"),
                            ("failed", "Ebaõnnestus"),
                        ],
                        db_index=True,
                        max_length=16,
                        verbose_name="Lugemise olek",
                    ),
                ),
                (
                    "failure_code",
                    models.CharField(blank=True, max_length=32, verbose_name="Vea kood"),
                ),
                ("first_seen_at", models.DateTimeField(verbose_name="Esmakordselt nähtud")),
                ("is_present", models.BooleanField(default=True, verbose_name="Koda.ee-s olemas")),
                ("source_order", models.PositiveIntegerField(default=0, verbose_name="Järjekord")),
                (
                    "warning_codes",
                    models.JSONField(blank=True, default=list, verbose_name="Hoiatuskoodid"),
                ),
            ],
            options={
                "verbose_name": "Avalik arvamusdokument",
                "verbose_name_plural": "Avalikud arvamusdokumendid",
                "ordering": ("snapshot", "page", "source_order"),
            },
        ),
        migrations.CreateModel(
            name="PublicOpinionFeedState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "last_checked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Viimati kontrollitud"
                    ),
                ),
                (
                    "last_successful_sync_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Viimane edukas sünkroonimine"
                    ),
                ),
                (
                    "last_changed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Viimati muutunud"),
                ),
                (
                    "last_result",
                    models.CharField(
                        choices=[
                            ("never_run", "Pole veel käivitatud"),
                            ("imported", "Imporditud"),
                            ("unchanged", "Muutumatu"),
                            ("failed", "Ebaõnnestus"),
                        ],
                        default="never_run",
                        max_length=16,
                        verbose_name="Viimane tulemus",
                    ),
                ),
                (
                    "last_error_summary",
                    models.CharField(
                        blank=True,
                        help_text="Puhastatud ja lühendatud. Ei sisalda aadresse ega failinimesid.",
                        max_length=500,
                        verbose_name="Viimane veateade",
                    ),
                ),
                (
                    "backfill_complete",
                    models.BooleanField(default=False, verbose_name="Ajalugu kogutud"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Muudetud")),
            ],
            options={
                "verbose_name": "Avaliku arvamusallika olek",
                "verbose_name_plural": "Avalike arvamusallikate olekud",
            },
        ),
        migrations.CreateModel(
            name="PublicOpinionPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("content_key", models.CharField(max_length=64, verbose_name="Sisu võti")),
                ("canonical_url", models.URLField(max_length=500, verbose_name="Aadress")),
                (
                    "page_type",
                    models.CharField(
                        choices=[
                            ("meie_arvamus", "Meie arvamus"),
                            ("news", "Uudis"),
                            ("other", "Muu Koda.ee arvamuskontekst"),
                        ],
                        db_index=True,
                        max_length=16,
                        verbose_name="Lehe liik",
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="Pealkiri")),
                ("listing_summary", models.TextField(blank=True, verbose_name="Loendi kokkuvõte")),
                ("body_text", models.TextField(blank=True, verbose_name="Lehe tekst")),
                (
                    "published_date",
                    models.DateField(blank=True, null=True, verbose_name="Avaldatud"),
                ),
                (
                    "opinion_evidence_codes",
                    models.JSONField(blank=True, default=list, verbose_name="Arvamustõendid"),
                ),
                (
                    "fetch_state",
                    models.CharField(
                        choices=[
                            ("fetched", "Loetud"),
                            ("carried", "Eelmisest ülekantud"),
                            ("failed", "Ebaõnnestus"),
                        ],
                        db_index=True,
                        max_length=16,
                        verbose_name="Lugemise olek",
                    ),
                ),
                (
                    "failure_code",
                    models.CharField(blank=True, max_length=32, verbose_name="Vea kood"),
                ),
                (
                    "content_hash",
                    models.CharField(blank=True, max_length=64, verbose_name="Sisu räsi"),
                ),
                ("first_seen_at", models.DateTimeField(verbose_name="Esmakordselt nähtud")),
                (
                    "last_fetched_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Viimati loetud"),
                ),
                ("is_present", models.BooleanField(default=True, verbose_name="Koda.ee-s olemas")),
            ],
            options={
                "verbose_name": "Avalik arvamusleht",
                "verbose_name_plural": "Avalikud arvamuslehed",
                "ordering": ("snapshot", "-published_date", "-id"),
            },
        ),
        migrations.CreateModel(
            name="PublicOpinionSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("observed_at", models.DateTimeField(verbose_name="Kogutud")),
                ("corpus_checksum", models.CharField(max_length=64, verbose_name="Korpuse räsi")),
                ("page_count", models.PositiveIntegerField(default=0, verbose_name="Lehti")),
                (
                    "document_count",
                    models.PositiveIntegerField(default=0, verbose_name="Dokumente"),
                ),
                (
                    "article_only_page_count",
                    models.PositiveIntegerField(default=0, verbose_name="Lehti ilma PDF-ita"),
                ),
                (
                    "listing_pages_fetched",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Loetud loendilehti"),
                ),
                (
                    "detail_pages_fetched",
                    models.PositiveIntegerField(default=0, verbose_name="Loetud lehti"),
                ),
                (
                    "documents_fetched",
                    models.PositiveIntegerField(default=0, verbose_name="Loetud dokumente"),
                ),
                (
                    "new_blob_count",
                    models.PositiveIntegerField(default=0, verbose_name="Uusi faile"),
                ),
                (
                    "known_blob_count",
                    models.PositiveIntegerField(default=0, verbose_name="Tuntud faile"),
                ),
                (
                    "invalid_document_count",
                    models.PositiveIntegerField(default=0, verbose_name="Vigaseid faile"),
                ),
                (
                    "failed_page_count",
                    models.PositiveIntegerField(default=0, verbose_name="Ebaõnnestunud lehti"),
                ),
                ("is_current", models.BooleanField(default=False, verbose_name="Kehtiv")),
            ],
            options={
                "verbose_name": "Avaliku arvamusallika hetkeseis",
                "verbose_name_plural": "Avaliku arvamusallika hetkeseisud",
                "ordering": ("-observed_at", "-id"),
            },
        ),
        migrations.RemoveConstraint(
            model_name="legalopiniondocumentrelation",
            name="legalopinionrelation_unique_entry_per_decision",
        ),
        migrations.RemoveConstraint(
            model_name="legalopinionmatchsnapshot",
            name="legalopinionmatch_unique_inputs",
        ),
        migrations.AddField(
            model_name="legalopiniondocumentrelation",
            name="blob",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="legal_work.opiniondocumentblob",
                verbose_name="Fail",
            ),
        ),
        migrations.AddField(
            model_name="legalopiniondocumentrelation",
            name="extraction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="legal_work.opiniondocumentextraction",
                verbose_name="Lugemine",
            ),
        ),
        migrations.AlterField(
            model_name="legalopiniondocumentrelation",
            name="entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="legal_work.opinioncatalogueentry",
                verbose_name="Privaatne kirje",
            ),
        ),
        migrations.AddField(
            model_name="legalopinionpagerelation",
            name="decision",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="page_relations",
                to="legal_work.legalopiniondecision",
                verbose_name="Otsus",
            ),
        ),
        migrations.AddField(
            model_name="publicopiniondocument",
            name="blob",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="public_documents",
                to="legal_work.opiniondocumentblob",
                verbose_name="Fail",
            ),
        ),
        migrations.AddField(
            model_name="publicopiniondocument",
            name="extraction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="public_documents",
                to="legal_work.opiniondocumentextraction",
                verbose_name="Lugemine",
            ),
        ),
        migrations.AddField(
            model_name="legalopiniondocumentrelation",
            name="public_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="legal_work.publicopiniondocument",
                verbose_name="Avalik dokument",
            ),
        ),
        migrations.RunPython(_backfill_relation_documents, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="legalopiniondocumentrelation",
            name="blob",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="legal_work.opiniondocumentblob",
                verbose_name="Fail",
            ),
        ),
        migrations.AddConstraint(
            model_name="legalopiniondocumentrelation",
            constraint=models.UniqueConstraint(
                fields=("decision", "blob"), name="legalopinionrelation_unique_blob_per_decision"
            ),
        ),
        migrations.AddConstraint(
            model_name="legalopiniondocumentrelation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("entry__isnull", False), ("public_document__isnull", False), _connector="OR"
                ),
                name="legalopinionrelation_has_provenance",
            ),
        ),
        migrations.AddField(
            model_name="publicopinionfeedstate",
            name="source",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="public_opinion_feed_state",
                to="sources.datasource",
                verbose_name="Andmeallikas",
            ),
        ),
        migrations.AddField(
            model_name="publicopiniondocument",
            name="page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="legal_work.publicopinionpage",
                verbose_name="Leht",
            ),
        ),
        migrations.AddField(
            model_name="legalopinionpagerelation",
            name="page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="legal_work.publicopinionpage",
                verbose_name="Leht",
            ),
        ),
        migrations.AddField(
            model_name="publicopinionsnapshot",
            name="artifact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="public_opinion_snapshots",
                to="sources.sourceartifact",
                verbose_name="Algfail",
            ),
        ),
        migrations.AddField(
            model_name="publicopinionsnapshot",
            name="import_run",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="public_opinion_snapshot",
                to="sources.importrun",
                verbose_name="Impordikäivitus",
            ),
        ),
        migrations.AddField(
            model_name="publicopinionsnapshot",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="public_opinion_snapshots",
                to="sources.datasource",
                verbose_name="Andmeallikas",
            ),
        ),
        migrations.AddField(
            model_name="publicopinionpage",
            name="snapshot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pages",
                to="legal_work.publicopinionsnapshot",
                verbose_name="Hetkeseis",
            ),
        ),
        migrations.AddField(
            model_name="publicopinionfeedstate",
            name="current_snapshot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="legal_work.publicopinionsnapshot",
                verbose_name="Kehtiv hetkeseis",
            ),
        ),
        migrations.AddField(
            model_name="publicopiniondocument",
            name="snapshot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="legal_work.publicopinionsnapshot",
                verbose_name="Hetkeseis",
            ),
        ),
        migrations.AddField(
            model_name="legalopinionmatchsnapshot",
            name="public_opinion_snapshot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="match_snapshots",
                to="legal_work.publicopinionsnapshot",
                verbose_name="Avalik arvamuskorpus",
            ),
        ),
        migrations.AddConstraint(
            model_name="legalopinionmatchsnapshot",
            constraint=models.UniqueConstraint(
                fields=(
                    "legal_snapshot",
                    "opinion_catalogue_snapshot",
                    "public_opinion_snapshot",
                    "matcher_version",
                ),
                name="legalopinionmatch_unique_inputs",
                nulls_distinct=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="legalopinionpagerelation",
            constraint=models.UniqueConstraint(
                fields=("decision", "page"), name="legalopinionpagerel_unique_page_per_decision"
            ),
        ),
        migrations.AddConstraint(
            model_name="publicopinionsnapshot",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("source",),
                name="publicopinion_one_current_per_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="publicopinionsnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(("article_only_page_count__lte", models.F("page_count"))),
                name="publicopinion_article_only_within_pages",
            ),
        ),
        migrations.AddIndex(
            model_name="publicopinionpage",
            index=models.Index(
                fields=["snapshot", "page_type"], name="legal_work__snapsho_a5a22d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="publicopinionpage",
            index=models.Index(
                fields=["snapshot", "published_date"], name="legal_work__snapsho_be477f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="publicopinionpage",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "content_key"), name="publicopinionpage_unique_key_per_snapshot"
            ),
        ),
        migrations.AddConstraint(
            model_name="publicopinionpage",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "canonical_url"),
                name="publicopinionpage_unique_url_per_snapshot",
            ),
        ),
        migrations.AddConstraint(
            model_name="publicopinionpage",
            constraint=models.CheckConstraint(
                condition=models.Q(("canonical_url", ""), _negated=True),
                name="publicopinionpage_url_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="publicopinionpage",
            constraint=models.CheckConstraint(
                condition=models.Q(("title", ""), _negated=True),
                name="publicopinionpage_title_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="publicopinionpage",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("fetch_state", "fetched"), _negated=True),
                    models.Q(("body_text", ""), _negated=True),
                    _connector="OR",
                ),
                name="publicopinionpage_fetched_has_body",
            ),
        ),
        migrations.AddIndex(
            model_name="publicopiniondocument",
            index=models.Index(
                fields=["snapshot", "classification"], name="legal_work__snapsho_5f80a7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="publicopiniondocument",
            index=models.Index(
                fields=["snapshot", "filename_date"], name="legal_work__snapsho_b32c84_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="publicopiniondocument",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "pdf_url"), name="publicopiniondoc_unique_url_per_snapshot"
            ),
        ),
        migrations.AddConstraint(
            model_name="publicopiniondocument",
            constraint=models.CheckConstraint(
                condition=models.Q(("pdf_url", ""), _negated=True),
                name="publicopiniondoc_url_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="publicopiniondocument",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("extraction__isnull", True), ("blob__isnull", False), _connector="OR"
                ),
                name="publicopiniondoc_extraction_requires_blob",
            ),
        ),
    ]
