# Generated by Django 5.2.16 on 2026-08-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("legal_work", "0008_public_opinion_source"),
        ("sources", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="opinioncataloguesnapshot",
            name="opinioncatalogue_unique_manifest_and_extractor",
        ),
        migrations.AddConstraint(
            model_name="opinioncataloguesnapshot",
            constraint=models.UniqueConstraint(
                fields=(
                    "source",
                    "source_manifest_checksum",
                    "extractor_version",
                    "filename_normaliser_version",
                ),
                name="opinioncatalogue_unique_manifest_and_readers",
            ),
        ),
    ]
