# Generated by Django 5.2.16 on 2026-08-03 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("sources", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventProgrammeSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "schema_version",
                    models.CharField(
                        help_text="Töövihiku enda deklareeritud versioon, mitte importija oma.",
                        max_length=16,
                        verbose_name="Skeemi versioon",
                    ),
                ),
                (
                    "generator_version",
                    models.CharField(max_length=32, verbose_name="Generaatori versioon"),
                ),
                ("export_refreshed_at", models.DateTimeField(verbose_name="Eksport värskendatud")),
                ("imported_at", models.DateTimeField(auto_now_add=True, verbose_name="Imporditud")),
                ("is_current", models.BooleanField(default=False, verbose_name="Kehtiv")),
                (
                    "canonical_event_count",
                    models.PositiveIntegerField(default=0, verbose_name="Sündmusi kokku"),
                ),
                (
                    "dated_event_count",
                    models.PositiveIntegerField(default=0, verbose_name="Kuupäevaga sündmusi"),
                ),
                (
                    "linked_public_url_count",
                    models.PositiveIntegerField(default=0, verbose_name="Avaliku lingiga"),
                ),
                (
                    "review_required_count",
                    models.PositiveIntegerField(default=0, verbose_name="Ülevaatust vajavaid"),
                ),
                (
                    "repeated_service_code_count",
                    models.PositiveIntegerField(default=0, verbose_name="Korduvaid teenusekoode"),
                ),
                (
                    "excluded_event_count",
                    models.PositiveIntegerField(default=0, verbose_name="Välja jäetud ridu"),
                ),
                ("warning_count", models.PositiveIntegerField(default=0, verbose_name="Hoiatusi")),
                (
                    "artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="event_programme_snapshots",
                        to="sources.sourceartifact",
                        verbose_name="Algfail",
                    ),
                ),
                (
                    "import_run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="event_programme_snapshot",
                        to="sources.importrun",
                        verbose_name="Impordikäivitus",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="event_programme_snapshots",
                        to="sources.datasource",
                        verbose_name="Andmeallikas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sündmuste programmi hetkeseis",
                "verbose_name_plural": "Sündmuste programmi hetkeseisud",
                "ordering": ("-export_refreshed_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="EventProgrammeItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("event_id", models.CharField(max_length=32, verbose_name="Sündmuse ID")),
                (
                    "service_code",
                    models.CharField(db_index=True, max_length=16, verbose_name="Teenuse kood"),
                ),
                ("event_name", models.TextField(verbose_name="Nimi")),
                (
                    "start_date",
                    models.DateField(blank=True, db_index=True, null=True, verbose_name="Algus"),
                ),
                ("end_date", models.DateField(blank=True, null=True, verbose_name="Lõpp")),
                (
                    "event_year",
                    models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Aasta"),
                ),
                (
                    "event_month_key",
                    models.CharField(blank=True, max_length=7, verbose_name="Kuu võti"),
                ),
                (
                    "event_month_label",
                    models.CharField(blank=True, max_length=16, verbose_name="Kuu"),
                ),
                (
                    "event_quarter",
                    models.CharField(blank=True, max_length=2, verbose_name="Kvartal"),
                ),
                (
                    "event_status",
                    models.CharField(
                        choices=[
                            ("past", "Toimunud"),
                            ("ongoing", "Käib"),
                            ("upcoming", "Tulemas"),
                            ("date_unknown", "Kuupäev teadmata"),
                        ],
                        db_index=True,
                        max_length=16,
                        verbose_name="Seisund",
                    ),
                ),
                (
                    "tag_key",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, verbose_name="Sildi võti"
                    ),
                ),
                ("tag_label", models.CharField(blank=True, max_length=64, verbose_name="Silt")),
                (
                    "event_type_key",
                    models.CharField(
                        blank=True, db_index=True, max_length=32, verbose_name="Tüübi võti"
                    ),
                ),
                (
                    "event_type_label",
                    models.CharField(blank=True, max_length=64, verbose_name="Tüüp"),
                ),
                (
                    "delivery_mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("onsite", "Kohapeal"),
                            ("online", "Veebis"),
                            ("hybrid", "Hübriid"),
                        ],
                        max_length=16,
                        verbose_name="Toimumisviis",
                    ),
                ),
                (
                    "include_status",
                    models.CharField(
                        choices=[("YES", "Arvestatud"), ("REVIEW", "Ülevaatamisel")],
                        max_length=8,
                        verbose_name="Arvestamise olek",
                    ),
                ),
                (
                    "public_url",
                    models.URLField(blank=True, max_length=500, verbose_name="Avalik viide"),
                ),
                (
                    "public_link_status",
                    models.CharField(
                        choices=[
                            ("not_linked", "Lingita"),
                            ("linked_embedded_latest", "Lingitud (viimane)"),
                            ("linked_embedded_earlier", "Lingitud (varasem)"),
                            ("rejected_off_domain", "Tagasi lükatud (võõras domeen)"),
                        ],
                        max_length=32,
                        verbose_name="Lingi olek",
                    ),
                ),
                ("source_year", models.PositiveSmallIntegerField(verbose_name="Lähteaasta")),
                ("source_sheet", models.CharField(max_length=32, verbose_name="Lähteleht")),
                ("source_row", models.PositiveIntegerField(verbose_name="Lähterida")),
                (
                    "source_occurrence_count",
                    models.PositiveIntegerField(verbose_name="Ridu allikas"),
                ),
                (
                    "date_parse_status",
                    models.CharField(
                        choices=[
                            ("parsed_single", "Üks kuupäev"),
                            ("parsed_range", "Vahemik"),
                            ("unparsed", "Lugemata"),
                            ("ambiguous", "Mitmetähenduslik"),
                            ("invalid", "Vigane"),
                        ],
                        max_length=16,
                        verbose_name="Kuupäeva lugemine",
                    ),
                ),
                (
                    "review_required",
                    models.BooleanField(db_index=True, verbose_name="Vajab ülevaatust"),
                ),
                (
                    "warning_codes",
                    models.JSONField(blank=True, default=list, verbose_name="Hoiatuskoodid"),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="event_programme.eventprogrammesnapshot",
                        verbose_name="Hetkeseis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Programmi sündmus",
                "verbose_name_plural": "Programmi sündmused",
                "ordering": ("-start_date", "event_name", "event_id"),
            },
        ),
        migrations.CreateModel(
            name="EventProgrammeFeedState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "last_checked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Viimati kontrollitud"
                    ),
                ),
                (
                    "last_successful_sync_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Viimane edukas sünkroonimine"
                    ),
                ),
                (
                    "last_changed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Viimati muutunud"),
                ),
                (
                    "last_result",
                    models.CharField(
                        choices=[
                            ("never_run", "Pole veel käivitatud"),
                            ("imported", "Imporditud"),
                            ("unchanged", "Muutumatu"),
                            ("failed", "Ebaõnnestus"),
                        ],
                        default="never_run",
                        max_length=16,
                        verbose_name="Viimane tulemus",
                    ),
                ),
                (
                    "last_error_summary",
                    models.CharField(
                        blank=True,
                        help_text="Puhastatud ja lühendatud. Ei sisalda tokeneid ega failisisu.",
                        max_length=500,
                        verbose_name="Viimane veateade",
                    ),
                ),
                (
                    "remote_modified_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Kaugfail muudetud"),
                ),
                (
                    "remote_etag",
                    models.CharField(blank=True, max_length=200, verbose_name="Kaugfaili etag"),
                ),
                (
                    "remote_size_bytes",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="Kaugfaili suurus"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Muudetud")),
                (
                    "source",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="event_programme_feed_state",
                        to="sources.datasource",
                        verbose_name="Andmeallikas",
                    ),
                ),
                (
                    "current_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="event_programme.eventprogrammesnapshot",
                        verbose_name="Kehtiv hetkeseis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sündmuste programmi andmevoo olek",
                "verbose_name_plural": "Sündmuste programmi andmevoo olekud",
            },
        ),
        migrations.AddConstraint(
            model_name="eventprogrammesnapshot",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("source",),
                name="eventprogramme_one_current_snapshot_per_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventprogrammesnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(("dated_event_count__lte", models.F("canonical_event_count"))),
                name="eventprogramme_dated_count_within_total",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventprogrammesnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("linked_public_url_count__lte", models.F("canonical_event_count"))
                ),
                name="eventprogramme_linked_count_within_total",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventprogrammesnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("review_required_count__lte", models.F("canonical_event_count"))
                ),
                name="eventprogramme_review_count_within_total",
            ),
        ),
        migrations.AddIndex(
            model_name="eventprogrammeitem",
            index=models.Index(
                fields=["snapshot", "-start_date"], name="event_progr_snapsho_ddabaa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventprogrammeitem",
            index=models.Index(
                fields=["snapshot", "event_status"], name="event_progr_snapsho_1f6d8c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventprogrammeitem",
            index=models.Index(
                fields=["snapshot", "tag_key"], name="event_progr_snapsho_207a97_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventprogrammeitem",
            index=models.Index(
                fields=["snapshot", "event_year"], name="event_progr_snapsho_bd0af1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventprogrammeitem",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "event_id"), name="eventprogrammeitem_unique_event_per_snapshot"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventprogrammeitem",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "service_code"),
                name="eventprogrammeitem_unique_service_code_per_snapshot",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventprogrammeitem",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "source_sheet", "source_row"),
                name="eventprogrammeitem_unique_source_row_per_snapshot",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventprogrammeitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("event_name", ""), _negated=True),
                name="eventprogrammeitem_name_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventprogrammeitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("end_date__isnull", True),
                    ("end_date__gte", models.F("start_date")),
                    _connector="OR",
                ),
                name="eventprogrammeitem_end_not_before_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventprogrammeitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("start_date__isnull", False), ("end_date__isnull", True), _connector="OR"
                ),
                name="eventprogrammeitem_end_requires_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventprogrammeitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("source_year__gte", 1)),
                name="eventprogrammeitem_source_year_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventprogrammeitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("source_occurrence_count__gte", 1)),
                name="eventprogrammeitem_occurrence_count_positive",
            ),
        ),
    ]
