# Generated by Django 5.2.16 on 2026-08-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event_programme", "0002_public_event_matching"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventprogrammeitem",
            name="added_date",
            field=models.DateField(blank=True, null=True, verbose_name="Programmi lisatud"),
        ),
        migrations.AddField(
            model_name="eventprogrammeitem",
            name="member_price_eur",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Liikme hind"
            ),
        ),
        migrations.AddField(
            model_name="eventprogrammeitem",
            name="nonmember_price_eur",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Mitteliikme hind",
            ),
        ),
        migrations.AddField(
            model_name="eventprogrammeitem",
            name="planning_lead_days",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Planeerimisvaru (päeva)"
            ),
        ),
        migrations.AddField(
            model_name="eventprogrammeitem",
            name="price_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("free", "Tasuta"),
                    ("paid", "Tasuline"),
                    ("mixed", "Osaliselt tasuline"),
                    ("tba", "Selgub hiljem"),
                    ("missing", "Hind teadmata"),
                    ("review", "Hind ülevaatamisel"),
                ],
                db_index=True,
                max_length=16,
                verbose_name="Hinna olek",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventprogrammeitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("member_price_eur__isnull", True),
                    ("member_price_eur__gte", 0),
                    _connector="OR",
                ),
                name="eventprogrammeitem_member_price_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventprogrammeitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("nonmember_price_eur__isnull", True),
                    ("nonmember_price_eur__gte", 0),
                    _connector="OR",
                ),
                name="eventprogrammeitem_nonmember_price_not_negative",
            ),
        ),
    ]
