# Generated by Django 5.2.16 on 2026-07-31 07:17

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("sources", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VisibilityEntryBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "observation_date",
                    models.DateField(db_index=True, verbose_name="Vaatluse kuupäev"),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text="Vaba tekst kuni 500 tähemärki. Ei sisalda isikuandmeid ega salajasi väärtusi.",
                        max_length=500,
                        verbose_name="Märkus",
                    ),
                ),
                (
                    "content_hash",
                    models.CharField(
                        help_text="Kanoonilise JSON-i räsi. Sama sisuga esitust ei avaldata kaks korda.",
                        max_length=64,
                        unique=True,
                        verbose_name="Sisu SHA-256",
                    ),
                ),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        help_text="Seob ühe esituse kõik vaatlused, impordid ja auditisündmused.",
                        verbose_name="Korrelatsiooni ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Loodud")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tühi tähendab kustutatud kasutajat.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visibility_batches",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Sisestaja",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nähtavuse sisestus",
                "verbose_name_plural": "Nähtavuse sisestused",
                "ordering": ("-observation_date", "-id"),
            },
        ),
        migrations.CreateModel(
            name="VisibilityObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "metric",
                    models.CharField(
                        choices=[
                            (
                                "newsletter_member_recipients",
                                "Liikmete uudiskirja aktiivsed saajad",
                            ),
                            (
                                "newsletter_nonmember_recipients",
                                "Mitteliikmete uudiskirja aktiivsed saajad",
                            ),
                            ("newsletter_overlap_recipients", "Mõlemas nimekirjas olevad saajad"),
                            ("facebook_followers", "Facebooki jälgijad"),
                            ("linkedin_followers", "LinkedIni jälgijad"),
                            ("instagram_followers", "Instagrami jälgijad"),
                            ("youtube_subscribers", "YouTube’i tellijad"),
                        ],
                        db_index=True,
                        max_length=48,
                        verbose_name="Näitaja",
                    ),
                ),
                (
                    "value",
                    models.PositiveIntegerField(
                        help_text="Täisarv. Selgesõneline 0 on päris väärtus; puuduv väärtus ei ole rida.",
                        verbose_name="Väärtus",
                    ),
                ),
                (
                    "collection_method",
                    models.CharField(
                        choices=[
                            ("manual", "Käsitsi sisestatud"),
                            ("automatic", "Automaatselt kogutud"),
                        ],
                        db_index=True,
                        default="manual",
                        max_length=16,
                        verbose_name="Kogumisviis",
                    ),
                ),
                (
                    "observation_date",
                    models.DateField(db_index=True, verbose_name="Vaatluse kuupäev"),
                ),
                (
                    "is_current_for_date",
                    models.BooleanField(default=False, verbose_name="Kehtiv selle kuupäeva kohta"),
                ),
                (
                    "published_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Avaldatud"),
                ),
                (
                    "artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visibility_observations",
                        to="sources.sourceartifact",
                        verbose_name="Algfail",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="observations",
                        to="visibility.visibilityentrybatch",
                        verbose_name="Sisestus",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visibility_observations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Sisestaja",
                    ),
                ),
                (
                    "import_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visibility_observations",
                        to="sources.importrun",
                        verbose_name="Impordikäivitus",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visibility_observations",
                        to="sources.datasource",
                        verbose_name="Andmeallikas",
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        help_text="Ainult sama näitaja ja sama kuupäeva parandus.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseded_by",
                        to="visibility.visibilityobservation",
                        verbose_name="Asendab vaatlust",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nähtavuse vaatlus",
                "verbose_name_plural": "Nähtavuse vaatlused",
                "ordering": ("-observation_date", "metric", "-id"),
            },
        ),
        migrations.CreateModel(
            name="WebsiteTrafficObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("observed_at", models.DateTimeField(db_index=True, verbose_name="Vaatluse aeg")),
                ("period_start", models.DateField(verbose_name="Perioodi algus")),
                ("period_end", models.DateField(verbose_name="Perioodi lõpp")),
                (
                    "sessions",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="Seansid"),
                ),
                (
                    "active_users",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Aktiivsed kasutajad"
                    ),
                ),
                (
                    "page_views",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Lehevaatamised"
                    ),
                ),
                ("is_current", models.BooleanField(default=False, verbose_name="Kehtiv")),
                ("imported_at", models.DateTimeField(auto_now_add=True, verbose_name="Imporditud")),
                (
                    "artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="website_traffic_observations",
                        to="sources.sourceartifact",
                        verbose_name="Algfail",
                    ),
                ),
                (
                    "import_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="website_traffic_observations",
                        to="sources.importrun",
                        verbose_name="Impordikäivitus",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="website_traffic_observations",
                        to="sources.datasource",
                        verbose_name="Andmeallikas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Veebiliikluse vaatlus",
                "verbose_name_plural": "Veebiliikluse vaatlused",
                "ordering": ("-period_end", "-id"),
            },
        ),
        migrations.AddIndex(
            model_name="visibilityentrybatch",
            index=models.Index(
                fields=["-observation_date", "-id"], name="visibility__observa_fbfcc9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="visibilityobservation",
            index=models.Index(
                fields=["metric", "-observation_date"], name="visibility__metric_d41651_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="visibilityobservation",
            index=models.Index(
                fields=["metric", "is_current_for_date", "-observation_date"],
                name="visibility__metric_2cb08b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="visibilityobservation",
            index=models.Index(fields=["batch", "metric"], name="visibility__batch_i_e42c2e_idx"),
        ),
        migrations.AddConstraint(
            model_name="visibilityobservation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current_for_date", True)),
                fields=("metric", "observation_date"),
                name="visibilityobservation_one_current_per_metric_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="visibilityobservation",
            constraint=models.UniqueConstraint(
                fields=("batch", "metric"), name="visibilityobservation_unique_metric_per_batch"
            ),
        ),
        migrations.AddConstraint(
            model_name="visibilityobservation",
            constraint=models.CheckConstraint(
                condition=models.Q(("value__gte", 0)),
                name="visibilityobservation_value_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="visibilityobservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("supersedes__isnull", True),
                    models.Q(("supersedes", models.F("id")), _negated=True),
                    _connector="OR",
                ),
                name="visibilityobservation_does_not_supersede_itself",
            ),
        ),
        migrations.AddIndex(
            model_name="websitetrafficobservation",
            index=models.Index(
                fields=["source", "-period_end"], name="visibility__source__eb4ed0_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="websitetrafficobservation",
            constraint=models.CheckConstraint(
                condition=models.Q(("period_end__gte", models.F("period_start"))),
                name="websitetraffic_period_end_not_before_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="websitetrafficobservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("sessions__isnull", True), ("sessions__gte", 0), _connector="OR"
                ),
                name="websitetraffic_sessions_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="websitetrafficobservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("active_users__isnull", True), ("active_users__gte", 0), _connector="OR"
                ),
                name="websitetraffic_active_users_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="websitetrafficobservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("page_views__isnull", True), ("page_views__gte", 0), _connector="OR"
                ),
                name="websitetraffic_page_views_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="websitetrafficobservation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("source",),
                name="websitetraffic_one_current_per_source",
            ),
        ),
    ]
