# Generated by Django 5.2.16 on 2026-08-07 06:42
#
# Purely additive: one new table, no column added to a populated one, no
# backfill and no constraint tightened. Nothing existing is read or rewritten,
# so this needs no populated predecessor-state test under the rule in
# `AGENTS.md`. The row itself is created on demand by `get_feed_state`, so an
# empty table is the correct state after this runs.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sources", "0001_initial"),
        ("visibility", "0002_alter_visibilityobservation_metric"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ga4FeedState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "last_checked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Viimati kontrollitud"
                    ),
                ),
                (
                    "last_successful_sync_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Viimane edukas sünkroonimine"
                    ),
                ),
                (
                    "last_changed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Viimati muutunud"),
                ),
                (
                    "last_result",
                    models.CharField(
                        choices=[
                            ("never_run", "Pole veel käivitatud"),
                            ("imported", "Imporditud"),
                            ("unchanged", "Muutumatu"),
                            ("failed", "Ebaõnnestus"),
                        ],
                        default="never_run",
                        max_length=16,
                        verbose_name="Viimane tulemus",
                    ),
                ),
                (
                    "last_error_summary",
                    models.CharField(
                        blank=True,
                        help_text="Puhastatud ja lühendatud. Ei sisalda võtmeid, tokeneid, property ID-d ega Google'i vastuse sisu.",
                        max_length=500,
                        verbose_name="Viimane veateade",
                    ),
                ),
                (
                    "last_period_end",
                    models.DateField(
                        blank=True,
                        help_text="Millise aruandepäevani on andmed kogutud.",
                        null=True,
                        verbose_name="Viimane kogutud päev",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Muudetud")),
                (
                    "current_observation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="visibility.websitetrafficobservation",
                        verbose_name="Kehtiv vaatlus",
                    ),
                ),
                (
                    "source",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ga4_feed_state",
                        to="sources.datasource",
                        verbose_name="Andmeallikas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Google Analyticsi andmevoo olek",
                "verbose_name_plural": "Google Analyticsi andmevoo olekud",
            },
        ),
    ]
