"""Give GA4 a reporting-day history instead of a single current reading.

`WebsiteTrafficObservation` carried `is_current` unique per **source**: one
current row in the entire table. That is a "latest reading" model, and it cannot
hold a five-year daily history at all — publishing yesterday retired the day
before it. It is replaced by `Ga4DailySnapshot`, whose current row is unique per
**reporting date**, plus the page and channel rows a day is made of.

## The existing rows are carried over, not dropped

Whatever the deployment has already collected becomes revision 1 of its own
reporting day, keeping its figures, its source, its artifact and its import run,
so the audit trail still leads from the published number back to the run that
produced it. `period_end` becomes `report_date`; the observations this collector
publishes have always been single days, so no period is being flattened.

Their checksum is computed here in exactly the canonical form the collector now
uses. A migrated day therefore reads as *unchanged* only if the next collection
finds the same figures — and it will not, because the new collector also asks
for new users, engaged sessions and engagement duration. The first run after
this migration republishes those days as revision 2, with the migrated row kept
as the superseded revision. That is the honest outcome: the day genuinely has
more measured about it than it did before.

Safe on an empty database and on a populated one. It reads what is there and
writes one row per existing observation; there is no assumption about how many
rows that is, including none.
"""

# Generated by Django 5.2.16 on 2026-08-09 17:38

import hashlib
import json

import django.db.models.deletion
from django.db import migrations, models


def carry_observations_into_daily_snapshots(apps, schema_editor):
    """Copy every website-traffic observation to a reporting-day revision."""
    Observation = apps.get_model("visibility", "WebsiteTrafficObservation")
    Snapshot = apps.get_model("visibility", "Ga4DailySnapshot")

    for observation in Observation.objects.all().order_by("period_end", "id"):
        Snapshot.objects.create(
            source_id=observation.source_id,
            artifact_id=observation.artifact_id,
            import_run_id=observation.import_run_id,
            report_date=observation.period_end,
            observed_at=observation.observed_at,
            checksum=_migrated_checksum(observation),
            revision=1,
            supersedes=None,
            # Only the row that was current stays current. A retired one is
            # history, and making it current for its own date would resurrect a
            # figure the application had already replaced.
            is_current_for_date=bool(observation.is_current),
            sessions=observation.sessions,
            active_users=observation.active_users,
            page_views=observation.page_views,
            # Never measured by the old collector. `None`, not `0`: it did not
            # report zero new users, it did not ask.
            new_users=None,
            engaged_sessions=None,
            user_engagement_seconds=None,
            has_page_detail=False,
            has_channel_detail=False,
        )


def _migrated_checksum(observation) -> str:
    """The canonical digest of this observation, in the collector's own form.

    Written out here rather than imported from `apps.visibility.ga4`: a
    migration must keep producing the same bytes years from now, and importing
    live code would let a later refactor silently change what a historical row
    claims its checksum was.
    """
    payload = {
        "schema": "2.0",
        "source": "ga4",
        "report_date": observation.period_end.isoformat(),
        "site": {
            "sessions": observation.sessions,
            "active_users": observation.active_users,
            "new_users": None,
            "page_views": observation.page_views,
            "engaged_sessions": None,
            "user_engagement_seconds": None,
        },
        "has_page_detail": False,
        "has_channel_detail": False,
        "pages": [],
        "channels": [],
    }
    canonical = json.dumps(payload, sort_keys=True, separators=(",", ":"), ensure_ascii=False)
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


def drop_carried_snapshots(apps, schema_editor):
    """Reverse: remove the carried rows so the old table is authoritative again.

    Only the rows this migration created can be identified in reverse, and by
    the time anyone reverses it the new table may hold collected history as
    well. Deleting all of it would throw away days the old model could never
    have held, so the reverse deliberately refuses rather than guessing.
    """
    Snapshot = apps.get_model("visibility", "Ga4DailySnapshot")
    if Snapshot.objects.exclude(revision=1).exists():
        raise RuntimeError(
            "Ga4DailySnapshot carries revisions this migration did not create. "
            "Reversing would delete collected history; do it by hand."
        )
    Snapshot.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("sources", "0001_initial"),
        ("visibility", "0003_ga4feedstate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ga4feedstate",
            name="current_observation",
        ),
        migrations.CreateModel(
            name="Ga4DailySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("report_date", models.DateField(db_index=True, verbose_name="Aruandepaev")),
                ("observed_at", models.DateTimeField(verbose_name="Kogumise aeg")),
                (
                    "checksum",
                    models.CharField(
                        help_text="SHA-256 normaliseeritud paevakomplektist, mitte Google'i vastusest.",
                        max_length=64,
                        verbose_name="Kontrollsumma",
                    ),
                ),
                ("revision", models.PositiveIntegerField(default=1, verbose_name="Redaktsioon")),
                (
                    "is_current_for_date",
                    models.BooleanField(default=False, verbose_name="Kehtiv sel paeval"),
                ),
                (
                    "sessions",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="Seansid"),
                ),
                (
                    "active_users",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Aktiivsed kasutajad"
                    ),
                ),
                (
                    "new_users",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Uued kasutajad"
                    ),
                ),
                (
                    "page_views",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Lehevaatamised"
                    ),
                ),
                (
                    "engaged_sessions",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Kaasatud seansid"
                    ),
                ),
                (
                    "user_engagement_seconds",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Kaasatuse kestus (s)"
                    ),
                ),
                (
                    "has_page_detail",
                    models.BooleanField(
                        default=False,
                        help_text="Kas selle paeva kohta koguti lehtede kaupa read. Vaar tahendab, et lehtede andmeid ei kusitud - mitte seda, et lehevaatamisi ei olnud.",
                        verbose_name="Lehekaupa kogutud",
                    ),
                ),
                (
                    "has_channel_detail",
                    models.BooleanField(
                        default=False,
                        help_text="Sama vahe: kusimata jaanud ei ole sama mis moodetud null.",
                        verbose_name="Kanalite kaupa kogutud",
                    ),
                ),
                ("imported_at", models.DateTimeField(auto_now_add=True, verbose_name="Imporditud")),
                (
                    "artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ga4_daily_snapshots",
                        to="sources.sourceartifact",
                        verbose_name="Algfail",
                    ),
                ),
                (
                    "import_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ga4_daily_snapshots",
                        to="sources.importrun",
                        verbose_name="Impordikaivitus",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ga4_daily_snapshots",
                        to="sources.datasource",
                        verbose_name="Andmeallikas",
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseded_by",
                        to="visibility.ga4dailysnapshot",
                        verbose_name="Asendab",
                    ),
                ),
            ],
            options={
                "verbose_name": "Google Analyticsi paev",
                "verbose_name_plural": "Google Analyticsi paevad",
                "ordering": ("-report_date", "-revision", "-id"),
            },
        ),
        migrations.CreateModel(
            name="Ga4ChannelDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("report_date", models.DateField(verbose_name="Aruandepaev")),
                ("channel", models.CharField(max_length=120, verbose_name="Kanal")),
                ("sessions", models.PositiveIntegerField(verbose_name="Seansid")),
                (
                    "engaged_sessions",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Kaasatud seansid"
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channels",
                        to="visibility.ga4dailysnapshot",
                        verbose_name="Paev",
                    ),
                ),
            ],
            options={
                "verbose_name": "Google Analyticsi kanalipaev",
                "verbose_name_plural": "Google Analyticsi kanalipaevad",
                "ordering": ("-report_date", "-sessions", "channel"),
            },
        ),
        migrations.AddField(
            model_name="ga4feedstate",
            name="current_snapshot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="visibility.ga4dailysnapshot",
                verbose_name="Viimane avaldatud paev",
            ),
        ),
        migrations.CreateModel(
            name="Ga4PageDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("report_date", models.DateField(verbose_name="Aruandepaev")),
                ("path", models.CharField(max_length=500, verbose_name="Lehe tee")),
                (
                    "raw_path",
                    models.CharField(
                        blank=True,
                        help_text="Taidetud ainult siis, kui Google'i tee erines kanoonilisest.",
                        max_length=500,
                        verbose_name="Algne tee",
                    ),
                ),
                ("page_views", models.PositiveIntegerField(verbose_name="Lehevaatamised")),
                (
                    "active_users",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Aktiivsed kasutajad"
                    ),
                ),
                (
                    "user_engagement_seconds",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Kaasatuse kestus (s)"
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="visibility.ga4dailysnapshot",
                        verbose_name="Paev",
                    ),
                ),
            ],
            options={
                "verbose_name": "Google Analyticsi lehepaev",
                "verbose_name_plural": "Google Analyticsi lehepaevad",
                "ordering": ("-report_date", "-page_views", "path"),
            },
        ),
        migrations.RunPython(
            carry_observations_into_daily_snapshots,
            drop_carried_snapshots,
        ),
        migrations.DeleteModel(
            name="WebsiteTrafficObservation",
        ),
        migrations.AddIndex(
            model_name="ga4dailysnapshot",
            index=models.Index(
                fields=["source", "-report_date"], name="visibility__source__15aba9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ga4dailysnapshot",
            index=models.Index(
                condition=models.Q(("is_current_for_date", True)),
                fields=["report_date"],
                name="ga4daily_current_by_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="ga4dailysnapshot",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current_for_date", True)),
                fields=("source", "report_date"),
                name="ga4daily_one_current_per_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="ga4dailysnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision__gte", 1)), name="ga4daily_revision_positive"
            ),
        ),
        migrations.AddIndex(
            model_name="ga4channeldaily",
            index=models.Index(fields=["report_date"], name="visibility__report__952b0d_idx"),
        ),
        migrations.AddIndex(
            model_name="ga4channeldaily",
            index=models.Index(
                fields=["channel", "report_date"], name="visibility__channel_858a6c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="ga4channeldaily",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "channel"), name="ga4channel_unique_channel_per_snapshot"
            ),
        ),
        migrations.AddIndex(
            model_name="ga4pagedaily",
            index=models.Index(fields=["path", "report_date"], name="visibility__path_d7f190_idx"),
        ),
        migrations.AddIndex(
            model_name="ga4pagedaily",
            index=models.Index(fields=["report_date"], name="visibility__report__5b58e3_idx"),
        ),
        migrations.AddConstraint(
            model_name="ga4pagedaily",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "path"), name="ga4page_unique_path_per_snapshot"
            ),
        ),
    ]
