# Generated by Django 5.2.16 on 2026-08-10 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sources", "0001_initial"),
        ("visibility", "0004_ga4_daily_history"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visibilityobservation",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="observations",
                to="visibility.visibilityentrybatch",
                verbose_name="Sisestus",
            ),
        ),
        migrations.CreateModel(
            name="SmailyAudienceSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("observed_on", models.DateField(db_index=True, verbose_name="Lugemise kuupäev")),
                ("observed_at", models.DateTimeField(verbose_name="Kogumise aeg")),
                (
                    "checksum",
                    models.CharField(
                        help_text="SHA-256 normaliseeritud lugemisest, mitte Smaily vastusest.",
                        max_length=64,
                        verbose_name="Kontrollsumma",
                    ),
                ),
                ("revision", models.PositiveIntegerField(default=1, verbose_name="Redaktsioon")),
                (
                    "is_current_for_date",
                    models.BooleanField(default=False, verbose_name="Kehtiv sel päeval"),
                ),
                ("imported_at", models.DateTimeField(auto_now_add=True, verbose_name="Imporditud")),
                (
                    "artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="smaily_audience_snapshots",
                        to="sources.sourceartifact",
                        verbose_name="Algfail",
                    ),
                ),
                (
                    "import_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="smaily_audience_snapshots",
                        to="sources.importrun",
                        verbose_name="Impordikaivitus",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="smaily_audience_snapshots",
                        to="sources.datasource",
                        verbose_name="Andmeallikas",
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseded_by",
                        to="visibility.smailyaudiencesnapshot",
                        verbose_name="Asendab",
                    ),
                ),
            ],
            options={
                "verbose_name": "Smaily auditooriumi lugemine",
                "verbose_name_plural": "Smaily auditooriumi lugemised",
                "ordering": ("-observed_on", "-revision", "-id"),
            },
        ),
        migrations.CreateModel(
            name="SmailyFeedState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "last_checked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Viimati kontrollitud"
                    ),
                ),
                (
                    "last_successful_sync_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Viimane edukas sünkroonimine"
                    ),
                ),
                (
                    "last_changed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Viimati muutunud"),
                ),
                (
                    "last_result",
                    models.CharField(
                        choices=[
                            ("never_run", "Pole veel käivitatud"),
                            ("imported", "Imporditud"),
                            ("unchanged", "Muutumatu"),
                            ("failed", "Ebaõnnestus"),
                        ],
                        default="never_run",
                        max_length=16,
                        verbose_name="Viimane tulemus",
                    ),
                ),
                (
                    "last_error_summary",
                    models.CharField(
                        blank=True,
                        help_text="Puhastatud ja lühendatud. Ei sisalda API kasutajat, parooli, alamdomeeni ega Smaily vastuse sisu.",
                        max_length=500,
                        verbose_name="Viimane veateade",
                    ),
                ),
                (
                    "last_period_end",
                    models.DateField(
                        blank=True,
                        help_text="Millise lugemispäevani on andmed kogutud.",
                        null=True,
                        verbose_name="Viimane kogutud päev",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Muudetud")),
                (
                    "current_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="visibility.smailyaudiencesnapshot",
                        verbose_name="Viimane avaldatud lugemine",
                    ),
                ),
                (
                    "source",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="smaily_feed_state",
                        to="sources.datasource",
                        verbose_name="Andmeallikas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Smaily andmevoo olek",
                "verbose_name_plural": "Smaily andmevoo olekud",
            },
        ),
        migrations.CreateModel(
            name="SmailySegmentDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("observed_on", models.DateField(verbose_name="Lugemise kuupäev")),
                ("segment_id", models.PositiveIntegerField(verbose_name="Smaily segmendi tunnus")),
                (
                    "name",
                    models.CharField(blank=True, max_length=200, verbose_name="Segmendi nimi"),
                ),
                ("subscribers", models.PositiveIntegerField(verbose_name="Tellijaid")),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="visibility.smailyaudiencesnapshot",
                        verbose_name="Lugemine",
                    ),
                ),
            ],
            options={
                "verbose_name": "Smaily segmendi lugemine",
                "verbose_name_plural": "Smaily segmentide lugemised",
                "ordering": ("-observed_on", "-subscribers", "segment_id"),
            },
        ),
        migrations.AddIndex(
            model_name="smailyaudiencesnapshot",
            index=models.Index(
                fields=["source", "-observed_on"], name="visibility__source__9a40e1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="smailyaudiencesnapshot",
            index=models.Index(
                condition=models.Q(("is_current_for_date", True)),
                fields=["observed_on"],
                name="smailyaudience_current_by_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="smailyaudiencesnapshot",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current_for_date", True)),
                fields=("source", "observed_on"),
                name="smailyaudience_one_current_per_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="smailyaudiencesnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision__gte", 1)), name="smailyaudience_revision_positive"
            ),
        ),
        migrations.AddIndex(
            model_name="smailysegmentdaily",
            index=models.Index(
                fields=["segment_id", "observed_on"], name="visibility__segment_752090_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="smailysegmentdaily",
            index=models.Index(fields=["observed_on"], name="visibility__observe_1a8741_idx"),
        ),
        migrations.AddConstraint(
            model_name="smailysegmentdaily",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "segment_id"), name="smailysegment_unique_per_snapshot"
            ),
        ),
    ]
