# Generated by Django 5.2.16 on 2026-08-10 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sources", "0001_initial"),
        ("visibility", "0006_rename_smaily_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="SmailyCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "campaign_id",
                    models.PositiveBigIntegerField(
                        unique=True, verbose_name="Smaily kampaania tunnus"
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=300, verbose_name="Pealkiri")),
                (
                    "template_name",
                    models.CharField(
                        blank=True,
                        help_text="Väli, mille järgi uudiskiri tuvastatakse. Silt on kontol alati tühi.",
                        max_length=300,
                        verbose_name="Malli nimi",
                    ),
                ),
                (
                    "newsletter",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("newsletter_eteataja", "e-Teataja"),
                            ("newsletter_enews", "eNews"),
                            ("newsletter_evestnik", "e-Vestnik"),
                            ("facebook_followers", "Facebooki jälgijad"),
                            ("linkedin_followers", "LinkedIni jälgijad"),
                            ("instagram_followers", "Instagrami jälgijad"),
                            ("youtube_subscribers", "YouTube’i tellijad"),
                        ],
                        db_index=True,
                        help_text="Tühi, kui saadetis ei ole ühegi kolme uudiskirja number.",
                        max_length=48,
                        verbose_name="Uudiskiri",
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        blank=True,
                        help_text="e-Teataja läheb välja kahe saadetisena: liikmed ja mitteliikmed.",
                        max_length=20,
                        verbose_name="Sihtrühm",
                    ),
                ),
                ("status", models.CharField(blank=True, max_length=20, verbose_name="Olek")),
                ("created_at", models.DateTimeField(blank=True, null=True, verbose_name="Loodud")),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="Saadetud"
                    ),
                ),
                (
                    "first_seen_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Esmakordselt nähtud"),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(auto_now=True, verbose_name="Viimati nähtud"),
                ),
            ],
            options={
                "verbose_name": "Smaily kampaania",
                "verbose_name_plural": "Smaily kampaaniad",
                "ordering": ("-completed_at", "-campaign_id"),
                "indexes": [
                    models.Index(
                        fields=["newsletter", "-completed_at"],
                        name="visibility__newslet_239996_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SmailyCampaignStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("observed_at", models.DateTimeField(verbose_name="Kogumise aeg")),
                (
                    "checksum",
                    models.CharField(
                        help_text="SHA-256 normaliseeritud arvudest, mitte Smaily vastusest.",
                        max_length=64,
                        verbose_name="Kontrollsumma",
                    ),
                ),
                ("revision", models.PositiveIntegerField(default=1, verbose_name="Redaktsioon")),
                ("is_current", models.BooleanField(default=False, verbose_name="Kehtiv")),
                (
                    "total_count",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="Saadetud"),
                ),
                (
                    "delivered_count",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Kohale toimetatud"
                    ),
                ),
                (
                    "bounce_count",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Tagasi põrkunud"
                    ),
                ),
                (
                    "opened_count",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="Avamisi"),
                ),
                (
                    "click_count",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="Klikke"),
                ),
                (
                    "unique_click_count",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Unikaalseid klikke"
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="Vaatamisi"),
                ),
                (
                    "unique_view_count",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Unikaalseid vaatamisi"
                    ),
                ),
                (
                    "unsubscribe_count",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="Loobumisi"),
                ),
                (
                    "complaint_count",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="Kaebusi"),
                ),
                (
                    "forward_count",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Edasisaatmisi"
                    ),
                ),
                ("imported_at", models.DateTimeField(auto_now_add=True, verbose_name="Imporditud")),
                (
                    "artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="smaily_campaign_stats",
                        to="sources.sourceartifact",
                        verbose_name="Algfail",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statistics",
                        to="visibility.smailycampaign",
                        verbose_name="Kampaania",
                    ),
                ),
                (
                    "import_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="smaily_campaign_stats",
                        to="sources.importrun",
                        verbose_name="Impordikaivitus",
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseded_by",
                        to="visibility.smailycampaignstats",
                        verbose_name="Asendab",
                    ),
                ),
            ],
            options={
                "verbose_name": "Smaily kampaania statistika",
                "verbose_name_plural": "Smaily kampaaniate statistika",
                "ordering": ("-observed_at", "-revision", "-id"),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_current", True)),
                        fields=("campaign",),
                        name="smailycampaignstats_one_current",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("revision__gte", 1)),
                        name="smailycampaignstats_revision_positive",
                    ),
                ],
            },
        ),
    ]
