# Generated by Django 5.2.16 on 2026-08-11 02:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visibility", "0007_smaily_campaigns"),
    ]

    operations = [
        migrations.AddField(
            model_name="smailycampaign",
            name="preview_url",
            field=models.URLField(
                blank=True,
                help_text="Smaily enda eelvaade, kontrollitud enne salvestamist. Tühi, kui mall on kustutatud — kampaania ja tema statistika jäävad alles. Eelvaade kuulub MALLILE, mitte kampaaniale: sama malli jagavad kampaaniad viivad samale lehele ja see näitab malli praegust sisu.",
                max_length=500,
                verbose_name="Eelvaate aadress",
            ),
        ),
        migrations.AddField(
            model_name="smailycampaign",
            name="template_external_id",
            field=models.CharField(
                blank=True,
                help_text="Smaily malli tunnus, kui mall on veel olemas. Ei ole kampaania identiteet: mitu kampaaniat võivad kasutada sama malli.",
                max_length=40,
                verbose_name="Smaily malli tunnus",
            ),
        ),
    ]
