# Generated by Django 5.2.16 on 2026-08-16 04:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visibility", "0008_campaign_preview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ga4channeldaily",
            name="engaged_sessions",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Kaasatud külastused"
            ),
        ),
        migrations.AlterField(
            model_name="ga4channeldaily",
            name="sessions",
            field=models.PositiveIntegerField(verbose_name="Külastused"),
        ),
        migrations.AlterField(
            model_name="ga4dailysnapshot",
            name="engaged_sessions",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Kaasatud külastused"
            ),
        ),
        migrations.AlterField(
            model_name="ga4dailysnapshot",
            name="sessions",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Külastused"),
        ),
    ]
