# Generated by Django 5.2.16 on 2026-08-16 04:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visibility", "0009_alter_ga4channeldaily_engaged_sessions_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ga4PeriodUsers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Algus")),
                ("end_date", models.DateField(verbose_name="Lõpp")),
                ("active_users", models.PositiveIntegerField(verbose_name="Kasutajad")),
                ("fetched_at", models.DateTimeField(auto_now=True, verbose_name="Päritud")),
            ],
            options={
                "verbose_name": "Perioodi kasutajad",
                "verbose_name_plural": "Perioodi kasutajad",
                "ordering": ("-end_date", "-start_date"),
                "indexes": [
                    models.Index(
                        fields=["start_date", "end_date"], name="visibility__start_d_f3b8ae_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("start_date", "end_date"), name="ga4perioduser_one_row_per_range"
                    )
                ],
            },
        ),
    ]
