# Generated by Django 5.2.16 on 2026-07-28 15:11

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.sources.storage


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("slug", models.SlugField(max_length=64, unique=True, verbose_name="Lühinimi")),
                ("name", models.CharField(max_length=200, verbose_name="Nimi")),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("document", "Dokument"),
                            ("spreadsheet", "Tabel"),
                            ("registry", "Register"),
                            ("website", "Veebileht"),
                            ("manual", "Käsitsi sisestatud"),
                            ("other", "Muu"),
                        ],
                        default="other",
                        max_length=32,
                        verbose_name="Allika tüüp",
                    ),
                ),
                (
                    "authority_tier",
                    models.CharField(
                        choices=[
                            ("primary", "Esmane"),
                            ("secondary", "Teisene"),
                            ("supplementary", "Täiendav"),
                            ("unclassified", "Määramata"),
                        ],
                        default="unclassified",
                        max_length=32,
                        verbose_name="Autoriteedi tase",
                    ),
                ),
                (
                    "authority_rank",
                    models.PositiveSmallIntegerField(
                        default=100,
                        help_text="Väiksem number tähendab kõrgemat autoriteeti. Peab olema positiivne.",
                        verbose_name="Autoriteedi järk",
                    ),
                ),
                (
                    "responsible_person",
                    models.CharField(blank=True, max_length=200, verbose_name="Vastutaja"),
                ),
                (
                    "expected_update_frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Iga päev"),
                            ("weekly", "Iga nädal"),
                            ("monthly", "Iga kuu"),
                            ("quarterly", "Iga kvartal"),
                            ("annual", "Kord aastas"),
                            ("irregular", "Ebaregulaarne"),
                            ("unknown", "Teadmata"),
                        ],
                        default="unknown",
                        max_length=32,
                        verbose_name="Eeldatav uuendussagedus",
                    ),
                ),
                (
                    "stale_after_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Tühi tähendab, et aegumist ei jälgita.",
                        null=True,
                        verbose_name="Aegub päevade pärast",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Kirjeldus")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiivne")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Loodud")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Muudetud")),
            ],
            options={
                "verbose_name": "Andmeallikas",
                "verbose_name_plural": "Andmeallikad",
                "ordering": ("authority_rank", "name"),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("authority_rank__gte", 1)),
                        name="datasource_authority_rank_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("stale_after_days__isnull", True),
                            ("stale_after_days__gte", 0),
                            _connector="OR",
                        ),
                        name="datasource_stale_after_days_non_negative",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SourceArtifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "original_name",
                    models.CharField(
                        blank=True,
                        help_text="Ainult metaandmed. Salvestatud failitee ei kasuta seda nime.",
                        max_length=255,
                        verbose_name="Algne failinimi",
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(blank=True, max_length=128, verbose_name="MIME-tüüp"),
                ),
                (
                    "size_bytes",
                    models.PositiveBigIntegerField(default=0, verbose_name="Suurus baitides"),
                ),
                (
                    "sha256",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Arvutatakse serveris üleslaaditud sisust. Kliendi väärtust ei usaldata.",
                        max_length=64,
                        verbose_name="SHA-256",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        storage=apps.sources.storage.PrivateArtifactStorage(),
                        upload_to=apps.sources.storage.artifact_upload_path,
                        verbose_name="Privaatne fail",
                    ),
                ),
                (
                    "external_reference",
                    models.CharField(
                        blank=True,
                        help_text="Ei tohi sisaldada tunnuseid, tokeneid ega allkirjastatud parameetreid.",
                        max_length=500,
                        verbose_name="Väline viide",
                    ),
                ),
                (
                    "access_level",
                    models.CharField(
                        choices=[
                            ("staff_only", "Ainult töötajad"),
                            ("restricted", "Piiratud (ainult superkasutaja)"),
                        ],
                        default="staff_only",
                        max_length=32,
                        verbose_name="Ligipääsutase",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Registreeritud"),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="artifacts",
                        to="sources.datasource",
                        verbose_name="Andmeallikas",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_artifacts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registreerija",
                    ),
                ),
            ],
            options={
                "verbose_name": "Algfail",
                "verbose_name_plural": "Algfailid",
                "ordering": ("-uploaded_at", "-id"),
                "permissions": [("download_sourceartifact", "Võib alla laadida algfaili")],
            },
        ),
        migrations.CreateModel(
            name="ImportRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("importer_name", models.CharField(max_length=100, verbose_name="Importija")),
                ("schema_version", models.CharField(max_length=32, verbose_name="Skeemi versioon")),
                (
                    "import_key",
                    models.CharField(db_index=True, max_length=64, verbose_name="Impordivõti"),
                ),
                ("dry_run", models.BooleanField(default=True, verbose_name="Proovikäivitus")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ootel"),
                            ("running", "Töötab"),
                            ("succeeded", "Õnnestus"),
                            ("failed", "Ebaõnnestus"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=32,
                        verbose_name="Olek",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Alustatud"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Lõpetatud"),
                ),
                ("rows_added", models.PositiveIntegerField(default=0, verbose_name="Lisatud ridu")),
                (
                    "rows_skipped",
                    models.PositiveIntegerField(default=0, verbose_name="Vahele jäetud ridu"),
                ),
                (
                    "rows_invalid",
                    models.PositiveIntegerField(default=0, verbose_name="Vigaseid ridu"),
                ),
                ("warnings", models.JSONField(blank=True, default=list, verbose_name="Hoiatused")),
                ("errors", models.JSONField(blank=True, default=list, verbose_name="Vead")),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, verbose_name="Korrelatsiooni ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Loodud")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Muudetud")),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_runs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Käivitaja",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="import_runs",
                        to="sources.datasource",
                        verbose_name="Andmeallikas",
                    ),
                ),
                (
                    "artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="import_runs",
                        to="sources.sourceartifact",
                        verbose_name="Algfail",
                    ),
                ),
            ],
            options={
                "verbose_name": "Impordikäivitus",
                "verbose_name_plural": "Impordikäivitused",
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.AddConstraint(
            model_name="sourceartifact",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("external_reference", ""), ("file__gt", "")),
                    models.Q(("external_reference__gt", ""), ("file", "")),
                    _connector="OR",
                ),
                name="sourceartifact_file_xor_external_reference",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceartifact",
            constraint=models.UniqueConstraint(
                condition=models.Q(("sha256", ""), _negated=True),
                fields=("source", "sha256"),
                name="sourceartifact_unique_source_checksum",
            ),
        ),
        migrations.AddConstraint(
            model_name="importrun",
            constraint=models.UniqueConstraint(
                condition=models.Q(("dry_run", False), ("status", "succeeded")),
                fields=("import_key",),
                name="importrun_unique_successful_live_import",
            ),
        ),
        migrations.AddConstraint(
            model_name="importrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("finished_at__isnull", True),
                    models.Q(
                        ("finished_at__gte", models.F("started_at")), ("started_at__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="importrun_finished_not_before_started",
            ),
        ),
        migrations.AddConstraint(
            model_name="importrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status__in", ("succeeded", "failed")), _negated=True),
                    ("finished_at__isnull", False),
                    _connector="OR",
                ),
                name="importrun_terminal_requires_finished_at",
            ),
        ),
        migrations.AddConstraint(
            model_name="importrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ("succeeded", "failed")),
                    ("finished_at__isnull", True),
                    _connector="OR",
                ),
                name="importrun_non_terminal_has_no_finished_at",
            ),
        ),
    ]
