# Generated by Django 5.2.16 on 2026-07-30 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("sources", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MembershipCountObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("observed_at", models.DateTimeField(verbose_name="Vaatluse aeg")),
                ("total_members", models.PositiveIntegerField(verbose_name="Liikmeid kokku")),
                ("is_current", models.BooleanField(default=False, verbose_name="Kehtiv")),
                ("imported_at", models.DateTimeField(auto_now_add=True, verbose_name="Imporditud")),
                (
                    "artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="membership_observations",
                        to="sources.sourceartifact",
                        verbose_name="Algfail",
                    ),
                ),
                (
                    "import_run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="membership_observation",
                        to="sources.importrun",
                        verbose_name="Impordikäivitus",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="membership_observations",
                        to="sources.datasource",
                        verbose_name="Andmeallikas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Liikmete arvu vaatlus",
                "verbose_name_plural": "Liikmete arvu vaatlused",
                "ordering": ("-observed_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="MembershipFeedState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "last_checked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Viimati kontrollitud"
                    ),
                ),
                (
                    "last_successful_sync_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Viimane edukas sünkroonimine"
                    ),
                ),
                (
                    "last_changed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Viimati muutunud"),
                ),
                (
                    "last_result",
                    models.CharField(
                        choices=[
                            ("never_run", "Pole veel käivitatud"),
                            ("imported", "Imporditud"),
                            ("unchanged", "Muutumatu"),
                            ("failed", "Ebaõnnestus"),
                        ],
                        default="never_run",
                        max_length=16,
                        verbose_name="Viimane tulemus",
                    ),
                ),
                (
                    "last_error_summary",
                    models.CharField(
                        blank=True,
                        help_text="Puhastatud ja lühendatud. Ei sisalda vastuse sisu.",
                        max_length=500,
                        verbose_name="Viimane veateade",
                    ),
                ),
                (
                    "remote_etag",
                    models.CharField(blank=True, max_length=200, verbose_name="Allika etag"),
                ),
                (
                    "remote_last_modified",
                    models.CharField(blank=True, max_length=100, verbose_name="Allika muutmisaeg"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Muudetud")),
                (
                    "current_observation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="membership.membershipcountobservation",
                        verbose_name="Kehtiv vaatlus",
                    ),
                ),
                (
                    "source",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="membership_feed_state",
                        to="sources.datasource",
                        verbose_name="Andmeallikas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Liikmeskonna andmevoo olek",
                "verbose_name_plural": "Liikmeskonna andmevoo olekud",
            },
        ),
        migrations.AddConstraint(
            model_name="membershipcountobservation",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_members__gt", 0)),
                name="membershipobservation_total_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="membershipcountobservation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("source",),
                name="membershipobservation_one_current_per_source",
            ),
        ),
    ]
