# Generated by Django 5.2.16 on 2026-07-30 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0001_initial"),
        ("sources", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InternalMembershipObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "external_snapshot_id",
                    models.CharField(
                        blank=True,
                        help_text="Ajaloolise paketi snapshot_id. Käsitsi sisestatud kirjel tühi.",
                        max_length=64,
                        verbose_name="Paketi kirje tunnus",
                    ),
                ),
                (
                    "observation_date",
                    models.DateField(db_index=True, verbose_name="Vaatluse kuupäev"),
                ),
                (
                    "observation_date_precision",
                    models.CharField(
                        choices=[("day", "Päev"), ("month", "Kuu"), ("year", "Aasta")],
                        default="day",
                        max_length=8,
                        verbose_name="Kuupäeva täpsus",
                    ),
                ),
                (
                    "source_kind",
                    models.CharField(
                        choices=[
                            ("merged_same_document", "Dokumendi enda seis"),
                            ("reported_comparison", "Võrdlusveerust tuletatud"),
                            ("manual", "Käsitsi sisestatud"),
                        ],
                        db_index=True,
                        max_length=32,
                        verbose_name="Tõendi liik",
                    ),
                ),
                (
                    "source_column_label",
                    models.CharField(blank=True, max_length=120, verbose_name="Lähteveeru silt"),
                ),
                (
                    "reported_year",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Aruandeaasta"
                    ),
                ),
                (
                    "total_members",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Liikmeid kokku"
                    ),
                ),
                (
                    "paid_members",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Tasunud liikmeid"
                    ),
                ),
                (
                    "membership_fees_received_eur",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Laekunud liikmemaks (EUR)",
                    ),
                ),
                (
                    "membership_fee_budget_eur",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Liikmemaksu eelarve (EUR)",
                    ),
                ),
                (
                    "membership_fee_collection_pct_reported",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        verbose_name="Raporteeritud laekumise protsent",
                    ),
                ),
                (
                    "new_members_ytd",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Uusi liikmeid aasta algusest"
                    ),
                ),
                (
                    "suspended_members",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Peatatud liikmeid"
                    ),
                ),
                (
                    "removed_members_ytd",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Väljaarvatuid aasta algusest"
                    ),
                ),
                (
                    "extraction_confidence",
                    models.CharField(
                        choices=[
                            ("high", "Kõrge"),
                            ("medium", "Keskmine"),
                            ("low", "Madal"),
                            ("manual_verified", "Käsitsi kinnitatud"),
                        ],
                        default="medium",
                        max_length=16,
                        verbose_name="Eraldamise kindlus",
                    ),
                ),
                (
                    "quality_status",
                    models.CharField(
                        choices=[
                            ("verified", "Kinnitatud"),
                            ("provisional", "Esialgne"),
                            ("review_required", "Vajab ülevaatamist"),
                            ("conflicted", "Vastuoluline"),
                            ("superseded", "Asendatud"),
                        ],
                        db_index=True,
                        default="verified",
                        max_length=16,
                        verbose_name="Kvaliteedi olek",
                    ),
                ),
                (
                    "is_preferred_for_date",
                    models.BooleanField(
                        default=False, verbose_name="Eelistatud selle kuupäeva kohta"
                    ),
                ),
                ("source_note", models.TextField(blank=True, verbose_name="Märkus")),
                (
                    "warning_codes",
                    models.JSONField(blank=True, default=list, verbose_name="Hoiatuskoodid"),
                ),
                ("imported_at", models.DateTimeField(auto_now_add=True, verbose_name="Imporditud")),
                (
                    "published_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Avaldatud"),
                ),
                (
                    "artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="internal_membership_observations",
                        to="sources.sourceartifact",
                        verbose_name="Algfail",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tühi tähendab imporditud kirjet või kustutatud kasutajat.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="internal_membership_observations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Sisestaja",
                    ),
                ),
                (
                    "import_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="internal_membership_observations",
                        to="sources.importrun",
                        verbose_name="Impordikäivitus",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="internal_membership_observations",
                        to="sources.datasource",
                        verbose_name="Andmeallikas",
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseded_by",
                        to="membership.internalmembershipobservation",
                        verbose_name="Asendab vaatlust",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sisemine liikmeskonna vaatlus",
                "verbose_name_plural": "Sisemised liikmeskonna vaatlused",
                "ordering": ("-observation_date", "-id"),
            },
        ),
        migrations.CreateModel(
            name="MembershipHistoricalSourceDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "external_source_id",
                    models.CharField(max_length=64, verbose_name="Dokumendi tunnus"),
                ),
                (
                    "relative_path",
                    models.CharField(
                        blank=True,
                        help_text="Ainult auditijälg. Ei kuvata tavakasutajale.",
                        max_length=400,
                        verbose_name="Suhteline asukoht",
                    ),
                ),
                (
                    "filename",
                    models.CharField(blank=True, max_length=255, verbose_name="Failinimi"),
                ),
                ("extension", models.CharField(blank=True, max_length=16, verbose_name="Laiend")),
                (
                    "file_sha256",
                    models.CharField(blank=True, max_length=64, verbose_name="Faili SHA-256"),
                ),
                (
                    "file_size_bytes",
                    models.PositiveBigIntegerField(default=0, verbose_name="Faili suurus"),
                ),
                (
                    "filesystem_modified_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Faili muutmisaeg"),
                ),
                (
                    "year_folder",
                    models.CharField(blank=True, max_length=120, verbose_name="Aastakaust"),
                ),
                (
                    "month_folder",
                    models.CharField(blank=True, max_length=120, verbose_name="Kuukaust"),
                ),
                (
                    "candidate_reason",
                    models.CharField(blank=True, max_length=200, verbose_name="Valiku põhjus"),
                ),
                (
                    "extraction_status",
                    models.CharField(blank=True, max_length=32, verbose_name="Eraldamise olek"),
                ),
                (
                    "observation_date",
                    models.DateField(blank=True, null=True, verbose_name="Vaatluse kuupäev"),
                ),
                (
                    "observation_date_precision",
                    models.CharField(
                        choices=[("day", "Päev"), ("month", "Kuu"), ("year", "Aasta")],
                        default="day",
                        max_length=8,
                        verbose_name="Kuupäeva täpsus",
                    ),
                ),
                (
                    "date_source",
                    models.CharField(blank=True, max_length=64, verbose_name="Kuupäeva päritolu"),
                ),
                (
                    "date_confidence",
                    models.CharField(
                        choices=[
                            ("high", "Kõrge"),
                            ("medium", "Keskmine"),
                            ("low", "Madal"),
                            ("manual_verified", "Käsitsi kinnitatud"),
                        ],
                        default="medium",
                        max_length=16,
                        verbose_name="Kuupäeva kindlus",
                    ),
                ),
                (
                    "document_title",
                    models.CharField(blank=True, max_length=400, verbose_name="Dokumendi pealkiri"),
                ),
                (
                    "document_year_claim",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Dokumendi aastaväide"
                    ),
                ),
                (
                    "warning_codes",
                    models.JSONField(blank=True, default=list, verbose_name="Hoiatuskoodid"),
                ),
                ("notes", models.CharField(blank=True, max_length=300, verbose_name="Märkused")),
                ("imported_at", models.DateTimeField(auto_now_add=True, verbose_name="Imporditud")),
                (
                    "import_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="membership_source_documents",
                        to="sources.importrun",
                        verbose_name="Impordikäivitus",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="membership_source_documents",
                        to="sources.datasource",
                        verbose_name="Andmeallikas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Liikmeskonna aruandedokument",
                "verbose_name_plural": "Liikmeskonna aruandedokumendid",
                "ordering": ("-observation_date", "external_source_id"),
            },
        ),
        migrations.CreateModel(
            name="MembershipDataIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "external_warning_id",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="Paketi hoiatuse tunnus"
                    ),
                ),
                (
                    "dataset",
                    models.CharField(db_index=True, max_length=64, verbose_name="Andmestik"),
                ),
                (
                    "record_key",
                    models.CharField(blank=True, max_length=120, verbose_name="Kirje võti"),
                ),
                (
                    "warning_code",
                    models.CharField(db_index=True, max_length=80, verbose_name="Hoiatuskood"),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[("info", "Info"), ("warning", "Hoiatus"), ("error", "Viga")],
                        db_index=True,
                        default="info",
                        max_length=16,
                        verbose_name="Raskusaste",
                    ),
                ),
                ("message", models.CharField(blank=True, max_length=500, verbose_name="Sõnum")),
                (
                    "raw_value",
                    models.CharField(
                        blank=True,
                        help_text="Lühendatud ja puhastatud. Ei sisalda dokumendi teksti.",
                        max_length=500,
                        verbose_name="Algne väärtus",
                    ),
                ),
                (
                    "suggested_action",
                    models.CharField(blank=True, max_length=300, verbose_name="Soovitatud samm"),
                ),
                (
                    "resolved",
                    models.BooleanField(db_index=True, default=False, verbose_name="Lahendatud"),
                ),
                ("resolution_note", models.TextField(blank=True, verbose_name="Lahenduse märkus")),
                (
                    "resolved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Lahendatud"),
                ),
                ("imported_at", models.DateTimeField(auto_now_add=True, verbose_name="Imporditud")),
                (
                    "import_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="membership_data_issues",
                        to="sources.importrun",
                        verbose_name="Impordikäivitus",
                    ),
                ),
                (
                    "observation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issues",
                        to="membership.internalmembershipobservation",
                        verbose_name="Vaatlus",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_membership_issues",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Lahendaja",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="membership_data_issues",
                        to="sources.datasource",
                        verbose_name="Andmeallikas",
                    ),
                ),
                (
                    "source_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issues",
                        to="membership.membershiphistoricalsourcedocument",
                        verbose_name="Lähtedokument",
                    ),
                ),
            ],
            options={
                "verbose_name": "Liikmeskonna andmeprobleem",
                "verbose_name_plural": "Liikmeskonna andmeprobleemid",
                "ordering": ("severity", "dataset", "record_key", "id"),
            },
        ),
        migrations.AddField(
            model_name="internalmembershipobservation",
            name="source_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="observations",
                to="membership.membershiphistoricalsourcedocument",
                verbose_name="Lähtedokument",
            ),
        ),
        migrations.CreateModel(
            name="MembershipMetricConflict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "observation_date",
                    models.DateField(db_index=True, verbose_name="Vaatluse kuupäev"),
                ),
                ("metric", models.CharField(db_index=True, max_length=64, verbose_name="Näitaja")),
                (
                    "warning_code",
                    models.CharField(blank=True, max_length=80, verbose_name="Hoiatuskood"),
                ),
                (
                    "distinct_values",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Erinevate väärtuste arv"
                    ),
                ),
                (
                    "values_summary",
                    models.CharField(
                        blank=True,
                        help_text="Ainult halduri vaade.",
                        max_length=500,
                        verbose_name="Väärtuste kokkuvõte",
                    ),
                ),
                (
                    "source_document_ids",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Lähtedokumentide tunnused"
                    ),
                ),
                (
                    "resolved",
                    models.BooleanField(db_index=True, default=False, verbose_name="Lahendatud"),
                ),
                ("resolution_note", models.TextField(blank=True, verbose_name="Lahenduse märkus")),
                (
                    "resolved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Lahendatud"),
                ),
                ("imported_at", models.DateTimeField(auto_now_add=True, verbose_name="Imporditud")),
                (
                    "import_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="membership_metric_conflicts",
                        to="sources.importrun",
                        verbose_name="Impordikäivitus",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_membership_conflicts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Lahendaja",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="membership_metric_conflicts",
                        to="sources.datasource",
                        verbose_name="Andmeallikas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Liikmeskonna näitaja vastuolu",
                "verbose_name_plural": "Liikmeskonna näitajate vastuolud",
                "ordering": ("-observation_date", "metric"),
            },
        ),
        migrations.CreateModel(
            name="MembershipMonthlyNewMemberValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("calendar_year", models.PositiveSmallIntegerField(verbose_name="Aasta")),
                ("calendar_month", models.PositiveSmallIntegerField(verbose_name="Kuu")),
                (
                    "new_members",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Tühi tähendab vastuolu või teadmata väärtust, mitte nulli.",
                        null=True,
                        verbose_name="Uusi liikmeid",
                    ),
                ),
                (
                    "value_status",
                    models.CharField(
                        choices=[
                            ("verified", "Kinnitatud"),
                            ("provisional_current_month", "Esialgne jooksev kuu"),
                            ("conflict", "Vastuoluline"),
                            ("manual_verified", "Käsitsi kinnitatud"),
                            ("superseded", "Asendatud"),
                        ],
                        db_index=True,
                        max_length=32,
                        verbose_name="Väärtuse olek",
                    ),
                ),
                (
                    "source_count",
                    models.PositiveIntegerField(default=0, verbose_name="Allikate arv"),
                ),
                (
                    "source_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Ainult dokumenditunnused. Ei sisalda failiteid ega sisu.",
                        verbose_name="Lähtedokumentide tunnused",
                    ),
                ),
                (
                    "earliest_source_observation_date",
                    models.DateField(blank=True, null=True, verbose_name="Varaseim lähtevaatlus"),
                ),
                (
                    "latest_source_observation_date",
                    models.DateField(blank=True, null=True, verbose_name="Hiliseim lähtevaatlus"),
                ),
                (
                    "warning_codes",
                    models.JSONField(blank=True, default=list, verbose_name="Hoiatuskoodid"),
                ),
                (
                    "conflicting_values",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Ainult halduri vaade. Ei kuvata tavakasutajale.",
                        verbose_name="Vastuolulised väärtused",
                    ),
                ),
                (
                    "is_current_for_month",
                    models.BooleanField(default=False, verbose_name="Kehtiv selle kuu kohta"),
                ),
                ("imported_at", models.DateTimeField(auto_now_add=True, verbose_name="Imporditud")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="membership_monthly_new_members",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Sisestaja",
                    ),
                ),
                (
                    "import_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="membership_monthly_new_members",
                        to="sources.importrun",
                        verbose_name="Impordikäivitus",
                    ),
                ),
                (
                    "selected_source_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="selected_monthly_values",
                        to="membership.membershiphistoricalsourcedocument",
                        verbose_name="Valitud lähtedokument",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="membership_monthly_new_members",
                        to="sources.datasource",
                        verbose_name="Andmeallikas",
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseded_by",
                        to="membership.membershipmonthlynewmembervalue",
                        verbose_name="Asendab väärtust",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kuu uute liikmete arv",
                "verbose_name_plural": "Kuu uute liikmete arvud",
                "ordering": ("-calendar_year", "-calendar_month", "-id"),
            },
        ),
        migrations.CreateModel(
            name="MembershipRemovalReason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "reason_key",
                    models.CharField(
                        choices=[
                            (
                                "dissolved_bankrupt_merged_inactive_missing",
                                "Likvideeritud, pankrotis, ühinenud, tegevuseta või kadunud",
                            ),
                            ("voluntary_no_service_value", "Vabatahtlik: ei näe teenuses väärtust"),
                            (
                                "voluntary_debt_financial_or_other",
                                "Vabatahtlik: võlgnevus, majanduslik või muu põhjus",
                            ),
                            ("other", "Muu"),
                            ("unknown", "Teadmata"),
                        ],
                        max_length=64,
                        verbose_name="Põhjus",
                    ),
                ),
                (
                    "reason_label_raw",
                    models.CharField(blank=True, max_length=300, verbose_name="Algne põhjuse silt"),
                ),
                (
                    "member_count",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="Liikmeid"),
                ),
                (
                    "removed_total_reported",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Raporteeritud väljaarvatuid kokku"
                    ),
                ),
                (
                    "extraction_confidence",
                    models.CharField(
                        choices=[
                            ("high", "Kõrge"),
                            ("medium", "Keskmine"),
                            ("low", "Madal"),
                            ("manual_verified", "Käsitsi kinnitatud"),
                        ],
                        default="medium",
                        max_length=16,
                        verbose_name="Eraldamise kindlus",
                    ),
                ),
                (
                    "warning_codes",
                    models.JSONField(blank=True, default=list, verbose_name="Hoiatuskoodid"),
                ),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="removal_reasons",
                        to="membership.internalmembershipobservation",
                        verbose_name="Vaatlus",
                    ),
                ),
            ],
            options={
                "verbose_name": "Liikmeskonnast lahkumise põhjus",
                "verbose_name_plural": "Liikmeskonnast lahkumise põhjused",
                "ordering": ("observation", "reason_key", "reason_label_raw"),
            },
        ),
        migrations.CreateModel(
            name="MembershipSizeMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("joined", "Liitunud"), ("removed", "Lahkunud")],
                        max_length=8,
                        verbose_name="Suund",
                    ),
                ),
                (
                    "size_band_key",
                    models.CharField(
                        choices=[
                            ("employees_1_4", "1–4 töötajat"),
                            ("employees_5_9", "5–9 töötajat"),
                            ("employees_10_19", "10–19 töötajat"),
                            ("employees_20_49", "20–49 töötajat"),
                            ("employees_50_99", "50–99 töötajat"),
                            ("employees_100_249", "100–249 töötajat"),
                            ("employees_250_499", "250–499 töötajat"),
                            ("employees_500_999", "500–999 töötajat"),
                            ("employees_1000_plus", "1000+ töötajat"),
                            ("supporter", "Toetajaliige"),
                        ],
                        max_length=32,
                        verbose_name="Suurusklass",
                    ),
                ),
                (
                    "size_band_label_raw",
                    models.CharField(blank=True, max_length=120, verbose_name="Algne klassi silt"),
                ),
                (
                    "member_count",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="Liikmeid"),
                ),
                (
                    "total_reported",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Raporteeritud kogusumma"
                    ),
                ),
                (
                    "extraction_confidence",
                    models.CharField(
                        choices=[
                            ("high", "Kõrge"),
                            ("medium", "Keskmine"),
                            ("low", "Madal"),
                            ("manual_verified", "Käsitsi kinnitatud"),
                        ],
                        default="medium",
                        max_length=16,
                        verbose_name="Eraldamise kindlus",
                    ),
                ),
                (
                    "warning_codes",
                    models.JSONField(blank=True, default=list, verbose_name="Hoiatuskoodid"),
                ),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="size_movements",
                        to="membership.internalmembershipobservation",
                        verbose_name="Vaatlus",
                    ),
                ),
            ],
            options={
                "verbose_name": "Liikmeskonna liikumine suurusklassiti",
                "verbose_name_plural": "Liikmeskonna liikumised suurusklassiti",
                "ordering": ("observation", "direction", "size_band_key"),
            },
        ),
        migrations.AddIndex(
            model_name="membershiphistoricalsourcedocument",
            index=models.Index(
                fields=["source", "-observation_date"], name="membership__source__fb6475_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="membershiphistoricalsourcedocument",
            constraint=models.UniqueConstraint(
                fields=("source", "external_source_id"), name="membershipsourcedoc_unique_source_id"
            ),
        ),
        migrations.AddIndex(
            model_name="membershipdataissue",
            index=models.Index(
                fields=["source", "severity", "resolved"], name="membership__source__feacad_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="membershipdataissue",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_warning_id", ""), _negated=True),
                fields=("source", "external_warning_id"),
                name="membershipdataissue_unique_external_warning",
            ),
        ),
        migrations.AddIndex(
            model_name="internalmembershipobservation",
            index=models.Index(
                fields=["source", "-observation_date"], name="membership__source__7e5cd0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="internalmembershipobservation",
            index=models.Index(
                fields=["source", "is_preferred_for_date", "-observation_date"],
                name="membership__source__25dcfa_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="internalmembershipobservation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_snapshot_id", ""), _negated=True),
                fields=("source", "external_snapshot_id"),
                name="internalobservation_unique_external_snapshot",
            ),
        ),
        migrations.AddConstraint(
            model_name="internalmembershipobservation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_preferred_for_date", True)),
                fields=("source", "observation_date"),
                name="internalobservation_one_preferred_per_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="internalmembershipobservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("total_members__isnull", True), ("total_members__gt", 0), _connector="OR"
                ),
                name="internalobservation_total_positive_when_present",
            ),
        ),
        migrations.AddConstraint(
            model_name="internalmembershipobservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("membership_fees_received_eur__isnull", True),
                    ("membership_fees_received_eur__gte", 0),
                    _connector="OR",
                ),
                name="internalobservation_fees_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="internalmembershipobservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("membership_fee_budget_eur__isnull", True),
                    ("membership_fee_budget_eur__gte", 0),
                    _connector="OR",
                ),
                name="internalobservation_budget_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="internalmembershipobservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("membership_fee_collection_pct_reported__isnull", True),
                    ("membership_fee_collection_pct_reported__gte", 0),
                    _connector="OR",
                ),
                name="internalobservation_collection_pct_non_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="membershipmetricconflict",
            index=models.Index(
                fields=["source", "resolved", "-observation_date"],
                name="membership__source__c44509_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="membershipmetricconflict",
            constraint=models.UniqueConstraint(
                fields=("source", "observation_date", "metric"),
                name="membershipmetricconflict_unique_metric_per_date",
            ),
        ),
        migrations.AddIndex(
            model_name="membershipmonthlynewmembervalue",
            index=models.Index(
                fields=["source", "calendar_year", "calendar_month"],
                name="membership__source__c6c180_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="membershipmonthlynewmembervalue",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current_for_month", True)),
                fields=("source", "calendar_year", "calendar_month"),
                name="membershipmonthly_one_current_per_month",
            ),
        ),
        migrations.AddConstraint(
            model_name="membershipmonthlynewmembervalue",
            constraint=models.CheckConstraint(
                condition=models.Q(("calendar_month__gte", 1), ("calendar_month__lte", 12)),
                name="membershipmonthly_month_in_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="membershipmonthlynewmembervalue",
            constraint=models.CheckConstraint(
                condition=models.Q(("calendar_year__gte", 1900)),
                name="membershipmonthly_year_plausible",
            ),
        ),
        migrations.AddConstraint(
            model_name="membershipmonthlynewmembervalue",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("value_status", "conflict"), _negated=True),
                    ("new_members__isnull", True),
                    _connector="OR",
                ),
                name="membershipmonthly_conflict_has_no_value",
            ),
        ),
        migrations.AddConstraint(
            model_name="membershipremovalreason",
            constraint=models.UniqueConstraint(
                fields=("observation", "reason_key", "reason_label_raw"),
                name="membershipremovalreason_unique_reason_per_observation",
            ),
        ),
        migrations.AddConstraint(
            model_name="membershipsizemovement",
            constraint=models.UniqueConstraint(
                fields=("observation", "direction", "size_band_key"),
                name="membershipsizemovement_unique_band_per_direction",
            ),
        ),
    ]
