# Generated by Django 5.2.16 on 2026-07-30 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0002_internal_membership_history"),
    ]

    operations = [
        migrations.AlterField(
            model_name="internalmembershipobservation",
            name="membership_fee_collection_pct_reported",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=8,
                null=True,
                verbose_name="Raporteeritud laekumise protsent",
            ),
        ),
    ]
