# Generated by Django 5.2.16 on 2026-08-11 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0003_widen_reported_collection_percentage"),
        ("sources", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membershipsizemovement",
            name="size_band_key",
            field=models.CharField(
                choices=[
                    ("employees_1_4", "1–4 töötajat"),
                    ("employees_5_9", "5–9 töötajat"),
                    ("employees_10_19", "10–19 töötajat"),
                    ("employees_20_49", "20–49 töötajat"),
                    ("employees_50_99", "50–99 töötajat"),
                    ("employees_100_249", "100–249 töötajat"),
                    ("employees_250_499", "250–499 töötajat"),
                    ("employees_500_999", "500–999 töötajat"),
                    ("employees_1000_plus", "1000+ töötajat"),
                    ("supporter", "Toetajaliige"),
                    ("group_company", "Grupi ettevõte"),
                    ("unknown", "Suurus teadmata"),
                ],
                max_length=32,
                verbose_name="Suurusklass",
            ),
        ),
        migrations.CreateModel(
            name="MembershipDecisionBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "external_batch_id",
                    models.CharField(max_length=64, verbose_name="Otsuse partii tunnus"),
                ),
                (
                    "batch_kind",
                    models.CharField(
                        choices=[
                            ("termination", "Liikmelisuse lõpetamine"),
                            ("suspension", "Liikmelisuse peatamine"),
                        ],
                        max_length=16,
                        verbose_name="Otsuse liik",
                    ),
                ),
                (
                    "as_of_date",
                    models.DateField(blank=True, null=True, verbose_name="Seisuga kuupäev"),
                ),
                (
                    "as_of_date_precision",
                    models.CharField(
                        choices=[("day", "Päev"), ("month", "Kuu"), ("year", "Aasta")],
                        default="day",
                        max_length=8,
                        verbose_name="Seisu täpsus",
                    ),
                ),
                (
                    "decision_date",
                    models.DateField(
                        blank=True,
                        help_text="Juhatuse otsuse kuupäev. Erineb seisuga kuupäevast.",
                        null=True,
                        verbose_name="Otsuse kuupäev",
                    ),
                ),
                (
                    "decision_reference",
                    models.CharField(blank=True, max_length=120, verbose_name="Otsuse viide"),
                ),
                (
                    "member_count",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Liikmeid otsuses"
                    ),
                ),
                (
                    "quality_status",
                    models.CharField(
                        choices=[
                            ("verified", "Kinnitatud"),
                            ("provisional", "Esialgne"),
                            ("review_required", "Vajab ülevaatamist"),
                            ("conflicted", "Vastuoluline"),
                            ("superseded", "Asendatud"),
                        ],
                        default="verified",
                        max_length=20,
                        verbose_name="Kvaliteedi olek",
                    ),
                ),
                (
                    "extraction_confidence",
                    models.CharField(
                        choices=[
                            ("high", "Kõrge"),
                            ("medium", "Keskmine"),
                            ("low", "Madal"),
                            ("manual_verified", "Käsitsi kinnitatud"),
                        ],
                        default="medium",
                        max_length=16,
                        verbose_name="Eraldamise kindlus",
                    ),
                ),
                (
                    "warning_codes",
                    models.JSONField(blank=True, default=list, verbose_name="Hoiatuskoodid"),
                ),
                ("imported_at", models.DateTimeField(auto_now_add=True, verbose_name="Imporditud")),
                (
                    "corroborating_document",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vormiline juhatuse otsus, mis kinnitab lisa loendi.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="corroborated_decision_batches",
                        to="membership.membershiphistoricalsourcedocument",
                        verbose_name="Kinnitav dokument",
                    ),
                ),
                (
                    "import_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="membership_decision_batches",
                        to="sources.importrun",
                        verbose_name="Impordikäivitus",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="membership_decision_batches",
                        to="sources.datasource",
                        verbose_name="Andmeallikas",
                    ),
                ),
                (
                    "source_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decision_batches",
                        to="membership.membershiphistoricalsourcedocument",
                        verbose_name="Lähtedokument",
                    ),
                ),
            ],
            options={
                "verbose_name": "Juhatuse otsuse partii",
                "verbose_name_plural": "Juhatuse otsuse partiid",
                "ordering": ("-as_of_date", "batch_kind", "external_batch_id"),
            },
        ),
        migrations.CreateModel(
            name="MembershipDecisionBatchReason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "reason_key",
                    models.CharField(
                        choices=[
                            (
                                "financial_difficulty_or_cost_cutting",
                                "Majanduslikud raskused või kokkuhoid",
                            ),
                            ("no_service_use_or_value", "Ei kasuta teenuseid või ei näe kasu"),
                            (
                                "activity_ceased_or_dormant",
                                "Tegevus lõpetatud, peatatud või minimaalne",
                            ),
                            (
                                "liquidation_bankruptcy_deregistered",
                                "Likvideerimine, pankrot või registrist kustutamine",
                            ),
                            (
                                "merger_restructuring_ownership_change",
                                "Ühinemine, ümberkorraldus või omanikuvahetus",
                            ),
                            ("own_request_unspecified", "Omal soovil, põhjust täpsustamata"),
                            ("other", "Muu"),
                            ("unknown", "Teadmata"),
                        ],
                        max_length=64,
                        verbose_name="Põhjus",
                    ),
                ),
                (
                    "member_count",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="Liikmeid"),
                ),
                (
                    "warning_codes",
                    models.JSONField(blank=True, default=list, verbose_name="Hoiatuskoodid"),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departure_reasons",
                        to="membership.membershipdecisionbatch",
                        verbose_name="Otsuse partii",
                    ),
                ),
            ],
            options={
                "verbose_name": "Otsuse partii lahkumispõhjus",
                "verbose_name_plural": "Otsuse partii lahkumispõhjused",
                "ordering": ("batch", "reason_key"),
            },
        ),
        migrations.CreateModel(
            name="MembershipDecisionBatchSizeMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "size_band_key",
                    models.CharField(
                        choices=[
                            ("employees_1_4", "1–4 töötajat"),
                            ("employees_5_9", "5–9 töötajat"),
                            ("employees_10_19", "10–19 töötajat"),
                            ("employees_20_49", "20–49 töötajat"),
                            ("employees_50_99", "50–99 töötajat"),
                            ("employees_100_249", "100–249 töötajat"),
                            ("employees_250_499", "250–499 töötajat"),
                            ("employees_500_999", "500–999 töötajat"),
                            ("employees_1000_plus", "1000+ töötajat"),
                            ("supporter", "Toetajaliige"),
                            ("group_company", "Grupi ettevõte"),
                            ("unknown", "Suurus teadmata"),
                        ],
                        max_length=32,
                        verbose_name="Suurusklass",
                    ),
                ),
                (
                    "member_count",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="Liikmeid"),
                ),
                (
                    "warning_codes",
                    models.JSONField(blank=True, default=list, verbose_name="Hoiatuskoodid"),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="size_movements",
                        to="membership.membershipdecisionbatch",
                        verbose_name="Otsuse partii",
                    ),
                ),
            ],
            options={
                "verbose_name": "Otsuse partii suurusjaotus",
                "verbose_name_plural": "Otsuse partii suurusjaotused",
                "ordering": ("batch", "size_band_key"),
            },
        ),
        migrations.CreateModel(
            name="MembershipNewMemberPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "external_period_id",
                    models.CharField(max_length=64, verbose_name="Perioodi tunnus"),
                ),
                (
                    "period_scope",
                    models.CharField(
                        choices=[
                            ("calendar_month", "Kalendrikuu"),
                            ("multi_month_period", "Mitmekuuline periood"),
                        ],
                        default="multi_month_period",
                        max_length=24,
                        verbose_name="Perioodi ulatus",
                    ),
                ),
                ("period_start", models.DateField(verbose_name="Perioodi algus")),
                ("period_end", models.DateField(verbose_name="Perioodi lõpp")),
                (
                    "new_members",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Uusi liikmeid"
                    ),
                ),
                (
                    "extraction_confidence",
                    models.CharField(
                        choices=[
                            ("high", "Kõrge"),
                            ("medium", "Keskmine"),
                            ("low", "Madal"),
                            ("manual_verified", "Käsitsi kinnitatud"),
                        ],
                        default="medium",
                        max_length=16,
                        verbose_name="Eraldamise kindlus",
                    ),
                ),
                (
                    "warning_codes",
                    models.JSONField(blank=True, default=list, verbose_name="Hoiatuskoodid"),
                ),
                ("imported_at", models.DateTimeField(auto_now_add=True, verbose_name="Imporditud")),
                (
                    "import_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="membership_new_member_periods",
                        to="sources.importrun",
                        verbose_name="Impordikäivitus",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="membership_new_member_periods",
                        to="sources.datasource",
                        verbose_name="Andmeallikas",
                    ),
                ),
                (
                    "source_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="new_member_periods",
                        to="membership.membershiphistoricalsourcedocument",
                        verbose_name="Lähtedokument",
                    ),
                ),
            ],
            options={
                "verbose_name": "Uute liikmete periood",
                "verbose_name_plural": "Uute liikmete perioodid",
                "ordering": ("period_start", "period_end"),
            },
        ),
        migrations.CreateModel(
            name="MembershipNewMemberSizeDistribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "size_band_key",
                    models.CharField(
                        choices=[
                            ("employees_1_4", "1–4 töötajat"),
                            ("employees_5_9", "5–9 töötajat"),
                            ("employees_10_19", "10–19 töötajat"),
                            ("employees_20_49", "20–49 töötajat"),
                            ("employees_50_99", "50–99 töötajat"),
                            ("employees_100_249", "100–249 töötajat"),
                            ("employees_250_499", "250–499 töötajat"),
                            ("employees_500_999", "500–999 töötajat"),
                            ("employees_1000_plus", "1000+ töötajat"),
                            ("supporter", "Toetajaliige"),
                            ("group_company", "Grupi ettevõte"),
                            ("unknown", "Suurus teadmata"),
                        ],
                        max_length=32,
                        verbose_name="Suurusklass",
                    ),
                ),
                (
                    "member_count",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="Liikmeid"),
                ),
                (
                    "warning_codes",
                    models.JSONField(blank=True, default=list, verbose_name="Hoiatuskoodid"),
                ),
                (
                    "monthly_value",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="size_distribution",
                        to="membership.membershipmonthlynewmembervalue",
                        verbose_name="Kuu väärtus",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="size_distribution",
                        to="membership.membershipnewmemberperiod",
                        verbose_name="Periood",
                    ),
                ),
            ],
            options={
                "verbose_name": "Uute liikmete suurusjaotus",
                "verbose_name_plural": "Uute liikmete suurusjaotused",
                "ordering": ("monthly_value", "period", "size_band_key"),
            },
        ),
        migrations.AddConstraint(
            model_name="membershipdecisionbatch",
            constraint=models.UniqueConstraint(
                fields=("source", "external_batch_id"),
                name="membershipdecisionbatch_unique_external_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="membershipdecisionbatchreason",
            constraint=models.UniqueConstraint(
                fields=("batch", "reason_key"),
                name="membershipdecisionbatchreason_unique_reason_per_batch",
            ),
        ),
        migrations.AddConstraint(
            model_name="membershipdecisionbatchsizemovement",
            constraint=models.UniqueConstraint(
                fields=("batch", "size_band_key"),
                name="membershipdecisionbatchsize_unique_band_per_batch",
            ),
        ),
        migrations.AddConstraint(
            model_name="membershipnewmemberperiod",
            constraint=models.UniqueConstraint(
                fields=("source", "external_period_id"),
                name="membershipnewmemberperiod_unique_external_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="membershipnewmemberperiod",
            constraint=models.CheckConstraint(
                condition=models.Q(("period_end__gte", models.F("period_start"))),
                name="membershipnewmemberperiod_end_not_before_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="membershipnewmembersizedistribution",
            constraint=models.UniqueConstraint(
                fields=("monthly_value", "size_band_key"),
                name="membershipnewmembersize_unique_band_per_month",
            ),
        ),
        migrations.AddConstraint(
            model_name="membershipnewmembersizedistribution",
            constraint=models.UniqueConstraint(
                fields=("period", "size_band_key"),
                name="membershipnewmembersize_unique_band_per_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="membershipnewmembersizedistribution",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("monthly_value__isnull", False), ("period__isnull", True)),
                    models.Q(("monthly_value__isnull", True), ("period__isnull", False)),
                    _connector="OR",
                ),
                name="membershipnewmembersize_exactly_one_parent",
            ),
        ),
    ]
