# Generated by Django 5.2.16 on 2026-08-13 05:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0004_internal_membership_batch_evidence"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershipnewmemberperiod",
            name="quality_status",
            field=models.CharField(
                choices=[
                    ("verified", "Kinnitatud"),
                    ("provisional", "Esialgne"),
                    ("review_required", "Vajab ülevaatamist"),
                    ("conflicted", "Vastuoluline"),
                    ("superseded", "Asendatud"),
                ],
                default="verified",
                max_length=20,
                verbose_name="Kvaliteedi olek",
            ),
        ),
    ]
