# Generated by Django 5.2.16 on 2026-08-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0004_internal_membership_batch_evidence"),
        ("sources", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="membershiphistoricalsourcedocument",
            name="membershipsourcedoc_unique_source_id",
        ),
        migrations.AddConstraint(
            model_name="membershiphistoricalsourcedocument",
            constraint=models.UniqueConstraint(
                fields=("source", "external_source_id", "import_run"),
                name="membershipsourcedoc_unique_source_id_per_run",
            ),
        ),
    ]
