# Generated by Django 5.2.16 on 2026-08-14 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0005_new_member_period_quality_status"),
        ("sources", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MembershipCompositionSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("snapshot_date", models.DateField(verbose_name="Seisuga")),
                (
                    "source_sha256",
                    models.CharField(max_length=64, verbose_name="Lähtefaili kontrollsumma"),
                ),
                (
                    "source_row_count",
                    models.PositiveIntegerField(verbose_name="Lähtefaili ridade arv"),
                ),
                (
                    "mapping_version",
                    models.CharField(max_length=16, verbose_name="Klassifikaatori versioon"),
                ),
                (
                    "sector_mapping_version",
                    models.CharField(
                        max_length=16, verbose_name="Tegevusala klassifikaatori versioon"
                    ),
                ),
                (
                    "median_tenure_days",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Mediaanstaaž päevades"
                    ),
                ),
                ("coverage_pct", models.JSONField(blank=True, default=dict, verbose_name="Kaetus")),
                ("is_current", models.BooleanField(default=True, verbose_name="Kehtiv")),
                ("imported_at", models.DateTimeField(auto_now_add=True, verbose_name="Imporditud")),
                (
                    "import_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="membership_composition_snapshots",
                        to="sources.importrun",
                        verbose_name="Impordikäivitus",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="membership_composition_snapshots",
                        to="sources.datasource",
                        verbose_name="Andmeallikas",
                    ),
                ),
                (
                    "superseded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supersedes",
                        to="membership.membershipcompositionsnapshot",
                        verbose_name="Asendatud kirjega",
                    ),
                ),
            ],
            options={
                "verbose_name": "Liikmeskonna koosseisu hetkeseis",
                "verbose_name_plural": "Liikmeskonna koosseisu hetkeseisud",
                "ordering": ("-snapshot_date", "-imported_at"),
            },
        ),
        migrations.CreateModel(
            name="MembershipCompositionValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("population", models.CharField(max_length=32, verbose_name="Populatsioon")),
                ("dimension", models.CharField(max_length=24, verbose_name="Mõõde")),
                ("category_key", models.CharField(max_length=32, verbose_name="Kategooria")),
                ("category_label", models.CharField(max_length=96, verbose_name="Kategooria nimi")),
                ("member_count", models.PositiveIntegerField(verbose_name="Liikmete arv")),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="membership.membershipcompositionsnapshot",
                        verbose_name="Hetkeseis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Koosseisu näitaja",
                "verbose_name_plural": "Koosseisu näitajad",
                "ordering": ("snapshot", "population", "dimension", "category_key"),
            },
        ),
        migrations.AddIndex(
            model_name="membershipcompositionsnapshot",
            index=models.Index(
                fields=["source", "is_current", "-snapshot_date"], name="mcompsnap_current_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="membershipcompositionsnapshot",
            constraint=models.UniqueConstraint(
                fields=("source", "source_sha256"),
                name="membershipcompositionsnapshot_unique_source_file",
            ),
        ),
        migrations.AddConstraint(
            model_name="membershipcompositionsnapshot",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("source",),
                name="membershipcompositionsnapshot_one_current_per_source",
            ),
        ),
        migrations.AddIndex(
            model_name="membershipcompositionvalue",
            index=models.Index(
                fields=["snapshot", "population", "dimension"], name="mcompval_lookup_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="membershipcompositionvalue",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "population", "dimension", "category_key"),
                name="membershipcompositionvalue_unique_category",
            ),
        ),
    ]
