# Generated by Django 5.2.16 on 2026-08-15 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0006_membership_composition"),
        ("sources", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberRegisterSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("snapshot_date", models.DateField(verbose_name="Seisuga")),
                (
                    "source_sha256",
                    models.CharField(max_length=64, verbose_name="Lähtefaili kontrollsumma"),
                ),
                (
                    "source_row_count",
                    models.PositiveIntegerField(verbose_name="Lähtefaili ridade arv"),
                ),
                ("is_current", models.BooleanField(default=True, verbose_name="Kehtiv")),
                ("imported_at", models.DateTimeField(auto_now_add=True, verbose_name="Imporditud")),
                (
                    "import_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="member_register_snapshots",
                        to="sources.importrun",
                        verbose_name="Impordikäivitus",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="member_register_snapshots",
                        to="sources.datasource",
                        verbose_name="Andmeallikas",
                    ),
                ),
                (
                    "superseded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supersedes",
                        to="membership.memberregistersnapshot",
                        verbose_name="Asendatud kirjega",
                    ),
                ),
            ],
            options={
                "verbose_name": "Liikmete nimekirja hetkeseis",
                "verbose_name_plural": "Liikmete nimekirja hetkeseisud",
                "ordering": ("-snapshot_date", "-imported_at"),
            },
        ),
        migrations.CreateModel(
            name="MemberRegisterEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nimi")),
                ("legal_form", models.CharField(blank=True, max_length=16, verbose_name="Vorm")),
                (
                    "member_number",
                    models.CharField(blank=True, max_length=16, verbose_name="Liikmenumber"),
                ),
                ("status_key", models.CharField(max_length=16, verbose_name="Staatus")),
                (
                    "status_label",
                    models.CharField(blank=True, max_length=32, verbose_name="Staatus allikas"),
                ),
                (
                    "registry_code",
                    models.CharField(
                        blank=True, max_length=16, null=True, verbose_name="Registrikood"
                    ),
                ),
                ("county", models.CharField(blank=True, max_length=64, verbose_name="Maakond")),
                ("city", models.CharField(blank=True, max_length=64, verbose_name="Linn või vald")),
                ("country", models.CharField(blank=True, max_length=64, verbose_name="Riik")),
                (
                    "employees",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="Töötajaid"),
                ),
                (
                    "membership_start",
                    models.DateField(blank=True, null=True, verbose_name="Liikmelisus algas"),
                ),
                (
                    "nace_code",
                    models.CharField(blank=True, max_length=8, verbose_name="EMTAK/NACE kood"),
                ),
                (
                    "nace_label",
                    models.CharField(blank=True, max_length=160, verbose_name="Tegevusala"),
                ),
                ("website", models.CharField(blank=True, max_length=200, verbose_name="Veebileht")),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="membership.memberregistersnapshot",
                        verbose_name="Hetkeseis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Liikmete nimekirja kirje",
                "verbose_name_plural": "Liikmete nimekirja kirjed",
                "ordering": ("snapshot", "name", "id"),
            },
        ),
        migrations.CreateModel(
            name="MemberDirectoryEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("registry_code", models.CharField(max_length=16, verbose_name="Registrikood")),
                ("profile_path", models.CharField(max_length=300, verbose_name="Profiili aadress")),
                ("first_seen_at", models.DateTimeField(verbose_name="Esmakordselt nähtud")),
                ("last_seen_at", models.DateTimeField(verbose_name="Viimati nähtud")),
                ("is_published", models.BooleanField(default=True, verbose_name="Avaldatud")),
                (
                    "unpublished_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Kataloogist kadunud"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Muudetud")),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="member_directory_entries",
                        to="sources.datasource",
                        verbose_name="Andmeallikas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Avaliku kataloogi kirje",
                "verbose_name_plural": "Avaliku kataloogi kirjed",
                "ordering": ("registry_code",),
                "indexes": [
                    models.Index(fields=["source", "is_published"], name="mdirentry_published_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "registry_code"),
                        name="memberdirectoryentry_unique_code_per_source",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="memberregistersnapshot",
            index=models.Index(
                fields=["source", "is_current", "-snapshot_date"], name="mregsnap_current_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="memberregistersnapshot",
            constraint=models.UniqueConstraint(
                fields=("source", "source_sha256"), name="memberregistersnapshot_unique_source_file"
            ),
        ),
        migrations.AddConstraint(
            model_name="memberregistersnapshot",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("source",),
                name="memberregistersnapshot_one_current_per_source",
            ),
        ),
        migrations.AddIndex(
            model_name="memberregisterentry",
            index=models.Index(fields=["snapshot", "name"], name="mregentry_name_idx"),
        ),
        migrations.AddIndex(
            model_name="memberregisterentry",
            index=models.Index(fields=["snapshot", "status_key"], name="mregentry_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="memberregisterentry",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "registry_code"),
                name="memberregisterentry_unique_code_per_snapshot",
            ),
        ),
    ]
