# Generated by Django 5.2.16 on 2026-08-11 14:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("sources", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "source_product_id",
                    models.PositiveBigIntegerField(
                        db_index=True, unique=True, verbose_name="Commerce toote ID"
                    ),
                ),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("document", "Lepingute näidised"),
                            ("event_registration", "Sündmused"),
                            ("physical_product", "Füüsilised tooted"),
                        ],
                        db_index=True,
                        max_length=32,
                        verbose_name="Tooteliik",
                    ),
                ),
                ("first_seen_on", models.DateField(verbose_name="Esmakordselt nähtud")),
                ("last_seen_on", models.DateField(verbose_name="Viimati nähtud")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "E-poe toode",
                "verbose_name_plural": "E-poe tooted",
                "ordering": ("source_product_id",),
            },
        ),
        migrations.CreateModel(
            name="ShopDailyFact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("report_date", models.DateField(db_index=True, verbose_name="Kuupäev")),
                (
                    "member_status",
                    models.CharField(
                        choices=[
                            ("member", "Liige"),
                            ("non_member", "Mitteliige"),
                            ("unknown", "Teadmata"),
                        ],
                        db_index=True,
                        default="unknown",
                        max_length=16,
                        verbose_name="Liikmestaatus",
                    ),
                ),
                (
                    "payment_class",
                    models.CharField(
                        choices=[
                            ("invoice", "Arve"),
                            ("bank_or_card", "Pangalink või kaart"),
                            ("unknown", "Teadmata"),
                        ],
                        db_index=True,
                        default="unknown",
                        max_length=16,
                        verbose_name="Makseviis",
                    ),
                ),
                ("currency", models.CharField(default="EUR", max_length=3, verbose_name="Valuuta")),
                ("order_count", models.PositiveIntegerField(verbose_name="Tellimusi")),
                (
                    "units",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Soetatud ühikuid",
                    ),
                ),
                (
                    "ordered_value_net",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Tellitud väärtus (KM-ta)",
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(db_index=True, default=True, verbose_name="Kehtiv"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "import_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shop_daily_facts",
                        to="sources.importrun",
                        verbose_name="Impordijooks",
                    ),
                ),
                (
                    "supersedes",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="superseded_by",
                        to="shop.shopdailyfact",
                        verbose_name="Asendab",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="daily_facts",
                        to="shop.shopproduct",
                        verbose_name="Toode",
                    ),
                ),
            ],
            options={
                "verbose_name": "E-poe päevafakt",
                "verbose_name_plural": "E-poe päevafaktid",
                "ordering": ("-report_date", "product_id"),
                "indexes": [
                    models.Index(
                        fields=["product", "report_date"], name="shop_shopda_product_e20c37_idx"
                    ),
                    models.Index(
                        fields=["report_date", "member_status"],
                        name="shop_shopda_report__0a0ed1_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_current", True)),
                        fields=(
                            "report_date",
                            "product",
                            "member_status",
                            "payment_class",
                            "currency",
                        ),
                        name="shopdailyfact_one_current_per_cell",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("units__gte", 0)),
                        name="shopdailyfact_units_not_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("ordered_value_net__gte", 0)),
                        name="shopdailyfact_value_not_negative",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ShopProductPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "page_role",
                    models.CharField(
                        choices=[
                            ("product", "Tooteleht"),
                            ("information", "Tutvustus"),
                            ("event", "Sündmuse leht"),
                        ],
                        db_index=True,
                        max_length=16,
                        verbose_name="Lehe roll",
                    ),
                ),
                ("path", models.CharField(db_index=True, max_length=500, verbose_name="Tee")),
                ("first_seen_on", models.DateField(verbose_name="Esmakordselt nähtud")),
                ("last_seen_on", models.DateField(verbose_name="Viimati nähtud")),
                (
                    "is_current",
                    models.BooleanField(db_index=True, default=True, verbose_name="Kehtiv"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "import_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shop_product_pages",
                        to="sources.importrun",
                        verbose_name="Impordijooks",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pages",
                        to="shop.shopproduct",
                        verbose_name="Toode",
                    ),
                ),
            ],
            options={
                "verbose_name": "E-poe toote leht",
                "verbose_name_plural": "E-poe toodete lehed",
                "ordering": ("product_id", "page_role", "path"),
                "indexes": [
                    models.Index(fields=["path", "page_role"], name="shop_shoppr_path_0bb073_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product", "page_role", "path"),
                        name="shopproductpage_unique_product_role_path",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_current", True)),
                        fields=("product", "page_role"),
                        name="shopproductpage_one_current_per_role",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("path__startswith", "/")),
                        name="shopproductpage_path_is_absolute",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ShopProductSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("observed_on", models.DateField(db_index=True, verbose_name="Vaatluse kuupäev")),
                ("title", models.TextField(verbose_name="Pealkiri")),
                (
                    "category_term_id",
                    models.PositiveIntegerField(
                        blank=True, db_index=True, null=True, verbose_name="Kategooria ID"
                    ),
                ),
                (
                    "category_name",
                    models.CharField(blank=True, max_length=200, verbose_name="Kategooria"),
                ),
                ("published", models.BooleanField(blank=True, null=True, verbose_name="Avaldatud")),
                (
                    "publicly_listed",
                    models.BooleanField(blank=True, null=True, verbose_name="E-poes nähtav"),
                ),
                (
                    "members_only",
                    models.BooleanField(blank=True, null=True, verbose_name="Ainult liikmele"),
                ),
                (
                    "list_price_net",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=14,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Hind (KM-ta)",
                    ),
                ),
                (
                    "member_price_net",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=14,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Liikme hind (KM-ta)",
                    ),
                ),
                ("currency", models.CharField(default="EUR", max_length=3, verbose_name="Valuuta")),
                (
                    "connected_event_node_id",
                    models.PositiveBigIntegerField(
                        blank=True, db_index=True, null=True, verbose_name="Seotud sündmuse node ID"
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(db_index=True, default=True, verbose_name="Kehtiv"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "import_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shop_product_snapshots",
                        to="sources.importrun",
                        verbose_name="Impordijooks",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="snapshots",
                        to="shop.shopproduct",
                        verbose_name="Toode",
                    ),
                ),
                (
                    "supersedes",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="superseded_by",
                        to="shop.shopproductsnapshot",
                        verbose_name="Asendab",
                    ),
                ),
            ],
            options={
                "verbose_name": "E-poe toote vaatlus",
                "verbose_name_plural": "E-poe toodete vaatlused",
                "ordering": ("-observed_on", "product_id"),
                "indexes": [
                    models.Index(
                        fields=["product", "-observed_on"], name="shop_shoppr_product_f592c1_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_current", True)),
                        fields=("product", "observed_on"),
                        name="shopproductsnapshot_one_current_per_day",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("list_price_net__isnull", True),
                            ("list_price_net__gte", 0),
                            _connector="OR",
                        ),
                        name="shopproductsnapshot_list_price_not_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("member_price_net__isnull", True),
                            ("member_price_net__gte", 0),
                            _connector="OR",
                        ),
                        name="shopproductsnapshot_member_price_not_negative",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ShopSourceState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("schema_version", models.CharField(max_length=16, verbose_name="Skeemi versioon")),
                ("source_as_of", models.DateField(verbose_name="Andmed seisuga")),
                ("coverage_start", models.DateField(verbose_name="Ajaloo algus")),
                ("coverage_end", models.DateField(verbose_name="Ajaloo lõpp")),
                (
                    "member_semantics_verified",
                    models.BooleanField(
                        default=False, verbose_name="Liikmestaatuse tähendus kinnitatud"
                    ),
                ),
                (
                    "public_listing_semantics_verified",
                    models.BooleanField(
                        default=False, verbose_name="E-poes nähtavuse tähendus kinnitatud"
                    ),
                ),
                ("content_checksum", models.CharField(max_length=64, verbose_name="Sisu räsi")),
                ("product_count", models.PositiveIntegerField(default=0, verbose_name="Tooteid")),
                ("fact_count", models.PositiveIntegerField(default=0, verbose_name="Päevafakte")),
                ("page_count", models.PositiveIntegerField(default=0, verbose_name="Lehti")),
                ("observed_at", models.DateTimeField(verbose_name="Imporditud")),
                (
                    "is_current",
                    models.BooleanField(db_index=True, default=True, verbose_name="Kehtiv"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "import_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shop_states",
                        to="sources.importrun",
                        verbose_name="Impordijooks",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shop_states",
                        to="sources.datasource",
                        verbose_name="Andmeallikas",
                    ),
                ),
            ],
            options={
                "verbose_name": "E-poe andmeallika olek",
                "verbose_name_plural": "E-poe andmeallika olekud",
                "ordering": ("-observed_at", "-id"),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_current", True)),
                        fields=("source",),
                        name="shopsourcestate_one_current_per_source",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("coverage_end__gte", models.F("coverage_start"))),
                        name="shopsourcestate_coverage_end_not_before_start",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("coverage_end__lte", models.F("source_as_of"))),
                        name="shopsourcestate_coverage_within_source_date",
                    ),
                ],
            },
        ),
    ]
