# Generated by Django 5.2.16 on 2026-08-12 03:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopdailyfact",
            name="order_count",
            field=models.PositiveIntegerField(verbose_name="Tellimusridu"),
        ),
    ]
