# Generated by Django 5.2.16 on 2026-08-12 04:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_alter_shopdailyfact_order_count"),
        ("sources", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopDailySummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("report_date", models.DateField(db_index=True, verbose_name="Kuupäev")),
                (
                    "product_type",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Tühi tähendab kõiki tooteliike kokku.",
                        max_length=32,
                        verbose_name="Tooteliik",
                    ),
                ),
                ("distinct_order_count", models.PositiveIntegerField(verbose_name="Eri tellimusi")),
                (
                    "is_current",
                    models.BooleanField(db_index=True, default=True, verbose_name="Kehtiv"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "E-poe päevakokkuvõte",
                "verbose_name_plural": "E-poe päevakokkuvõtted",
                "ordering": ("-report_date", "product_type"),
            },
        ),
        migrations.AddField(
            model_name="shopdailyfact",
            name="free_units",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Tasuta ühikuid",
            ),
        ),
        migrations.AddField(
            model_name="shopdailyfact",
            name="paid_units",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Tasulisi ühikuid",
            ),
        ),
        migrations.AddField(
            model_name="shopdailyfact",
            name="unknown_units",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Määramata ühikuid",
            ),
        ),
        migrations.AddConstraint(
            model_name="shopdailyfact",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("free_units__isnull", True),
                        ("paid_units__isnull", True),
                        ("unknown_units__isnull", True),
                    ),
                    models.Q(
                        ("free_units__isnull", False),
                        ("paid_units__isnull", False),
                        ("unknown_units__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="shopdailyfact_split_all_or_nothing",
            ),
        ),
        migrations.AddField(
            model_name="shopdailysummary",
            name="import_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shop_daily_summaries",
                to="sources.importrun",
                verbose_name="Impordijooks",
            ),
        ),
        migrations.AddField(
            model_name="shopdailysummary",
            name="supersedes",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="superseded_by",
                to="shop.shopdailysummary",
                verbose_name="Asendab",
            ),
        ),
        migrations.AddIndex(
            model_name="shopdailysummary",
            index=models.Index(
                fields=["report_date", "product_type"], name="shop_shopda_report__94acf8_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="shopdailysummary",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("report_date", "product_type"),
                name="shopdailysummary_one_current_per_day_and_type",
            ),
        ),
    ]
