# Generated by Django 5.2.16 on 2026-08-13 02:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_shopdailysummary_shopdailyfact_free_units_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopdailyfact",
            name="units",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Ostetud ühikuid",
            ),
        ),
    ]
