# Generated by Django 5.2.16 on 2026-07-28 15:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, verbose_name="Aeg"
                    ),
                ),
                ("action", models.CharField(db_index=True, max_length=64, verbose_name="Tegevus")),
                (
                    "object_type",
                    models.CharField(
                        db_index=True,
                        help_text="Loetav ka siis, kui objekt on hiljem kadunud.",
                        max_length=100,
                        verbose_name="Objekti tüüp",
                    ),
                ),
                (
                    "object_id",
                    models.CharField(db_index=True, max_length=64, verbose_name="Objekti ID"),
                ),
                (
                    "change_summary",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Redigeeritud: PIN-e, paroole, võtmeid ja failide sisu ei salvestata.",
                        verbose_name="Muudatuse kokkuvõte",
                    ),
                ),
                (
                    "correlation_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Seob ühe päringu või impordi sündmused omavahel.",
                        null=True,
                        verbose_name="Korrelatsiooni ID",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tühi tähendab süsteemset tegevust või kustutatud kasutajat.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Tegija",
                    ),
                ),
            ],
            options={
                "verbose_name": "Auditisündmus",
                "verbose_name_plural": "Auditisündmused",
                "ordering": ("-timestamp", "-id"),
                "indexes": [
                    models.Index(
                        fields=["object_type", "object_id"], name="audit_audit_object__0e78a5_idx"
                    ),
                    models.Index(
                        fields=["action", "-timestamp"], name="audit_audit_action_c194db_idx"
                    ),
                ],
            },
        ),
    ]
